# parameters_llm_analyst_0603_2337.py
# Auto-generated by llm_alpha_generator.py — 20260603_233730
# Model: gemini-3.5-flash | Fields: 20 | Expressions: 160 (incl. auto-TOP200 pairs)
# Run: cp parameters_llm_analyst_0603_2337.py parameters.py && python3 main.py

from commands import *
BATCH_NAME = 'llm_analyst_0603_2337'

BASE = {'neutralization': 'SUBINDUSTRY', 'decay': 6, 'truncation': 0.08, 'delay': 1, 'region': 'USA', 'universe': 'TOP3000'}
B500 = {**BASE, 'universe': 'TOP500'}
B200 = {**BASE, 'universe': 'TOP200'}
UNIV = {'TOP3000': BASE, 'TOP500': B500, 'TOP200': B200}

DATA = [
    # actual_cashflow_per_share_value_quarterly
    # Quarterly cash flow per share is a strong fundamental quality metric; combining its trend with short-term price momentum identifies mispriced value.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(actual_cashflow_per_share_value_quarterly, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(actual_cashflow_per_share_value_quarterly, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(actual_cashflow_per_share_value_quarterly, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(actual_cashflow_per_share_value_quarterly, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(actual_cashflow_per_share_value_quarterly, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(actual_cashflow_per_share_value_quarterly, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(actual_cashflow_per_share_value_quarterly, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(actual_cashflow_per_share_value_quarterly, 252))'},
    # actual_dividend_value_quarterly
    # Quarterly dividends represent shareholder yield and financial health, where positive changes or steady ranks signal quality.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(actual_dividend_value_quarterly, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(actual_dividend_value_quarterly, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(actual_dividend_value_quarterly, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(actual_dividend_value_quarterly, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(actual_dividend_value_quarterly, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(actual_dividend_value_quarterly, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(actual_dividend_value_quarterly, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(actual_dividend_value_quarterly, 252))'},
    # actual_eps_value_quarterly
    # Actual EPS measures fundamental profitability, and combining its trend with short-term price momentum identifies mispriced value.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(actual_eps_value_quarterly, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(actual_eps_value_quarterly, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(actual_eps_value_quarterly, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(actual_eps_value_quarterly, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(actual_eps_value_quarterly, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(actual_eps_value_quarterly, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(actual_eps_value_quarterly, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(actual_eps_value_quarterly, 252))'},
    # actual_sales_value_annual
    # Annual sales value is a slow-moving fundamental size metric; smoothing and ranking over a 1-year lookback captures long-term growth.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(actual_sales_value_annual, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(actual_sales_value_annual, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(actual_sales_value_annual, 42) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(actual_sales_value_annual, 42) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(actual_sales_value_annual, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(actual_sales_value_annual, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(actual_sales_value_annual, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(actual_sales_value_annual, 252))'},
    # actual_sales_value_quarterly
    # Quarterly sales provide a more frequent update on top-line growth, especially useful for financial services where revenue momentum is key.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(actual_sales_value_quarterly, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(actual_sales_value_quarterly, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(actual_sales_value_quarterly, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(actual_sales_value_quarterly, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(actual_sales_value_quarterly, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(actual_sales_value_quarterly, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(actual_sales_value_quarterly, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(actual_sales_value_quarterly, 252))'},
    # actuals_reporting_currency
    # Reporting currency acts as a categorical grouping factor; neutralizing momentum within currency groups removes FX translation biases.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(group_neutralize(close, actuals_reporting_currency), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(group_neutralize(close, actuals_reporting_currency), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(group_neutralize(close, actuals_reporting_currency), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(group_neutralize(close, actuals_reporting_currency), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(group_neutralize(close, actuals_reporting_currency), 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(group_neutralize(close, actuals_reporting_currency), 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(group_neutralize(close, actuals_reporting_currency), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(group_neutralize(close, actuals_reporting_currency), 252))'},
    # actuals_value_currency_code
    # Grouping by pricing currency allows us to rank assets within the same trading currency, eliminating cross-border currency noise.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(group_neutralize(close, actuals_value_currency_code), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(group_neutralize(close, actuals_value_currency_code), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(group_neutralize(close, actuals_value_currency_code), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(group_neutralize(close, actuals_value_currency_code), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(group_neutralize(close, actuals_value_currency_code), 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(group_neutralize(close, actuals_value_currency_code), 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(group_neutralize(close, actuals_value_currency_code), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(group_neutralize(close, actuals_value_currency_code), 252))'},
    # adj_net_income_avg
    # Average adjusted net income represents a clean consensus fundamental; ranking its historical trend highlights high-quality earnings growth.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(adj_net_income_avg, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(adj_net_income_avg, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(adj_net_income_avg, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(adj_net_income_avg, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(adj_net_income_avg, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(adj_net_income_avg, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(adj_net_income_avg, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(adj_net_income_avg, 252))'},
    # adj_net_income_median
    # Median adjusted net profit is robust to extreme analyst estimates, making its time-series rank a stable indicator of core profitability.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(adj_net_income_median, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(adj_net_income_median, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(adj_net_income_median, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(adj_net_income_median, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(adj_net_income_median, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(adj_net_income_median, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(adj_net_income_median, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(adj_net_income_median, 252))'},
    # adj_net_income_stddev
    # High standard deviation in analyst estimates indicates high uncertainty; shorting companies with rising uncertainty relative to price momentum captures the disagreement premium.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(adj_net_income_stddev, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(adj_net_income_stddev, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(adj_net_income_stddev, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(adj_net_income_stddev, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(adj_net_income_stddev, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(adj_net_income_stddev, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(adj_net_income_stddev, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(adj_net_income_stddev, 252))'},
    # anl4_adjusted_netincome_ft
    # Changes in forecast types (e.g., from new to revision) can signal changes in analyst coverage dynamics, captured via time-series ranks.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(anl4_adjusted_netincome_ft, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(anl4_adjusted_netincome_ft, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(anl4_adjusted_netincome_ft, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(anl4_adjusted_netincome_ft, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(anl4_adjusted_netincome_ft, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(anl4_adjusted_netincome_ft, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(anl4_adjusted_netincome_ft, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(anl4_adjusted_netincome_ft, 252))'},
    # anl4_ads1detailafv110_bk
    # Neutralizing or ranking within broker identifier groups helps control for broker-specific optimistic or pessimistic biases.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(group_neutralize(close, anl4_ads1detailafv110_bk), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(group_neutralize(close, anl4_ads1detailafv110_bk), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(group_neutralize(close, anl4_ads1detailafv110_bk), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(group_neutralize(close, anl4_ads1detailafv110_bk), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(group_neutralize(close, anl4_ads1detailafv110_bk), 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(group_neutralize(close, anl4_ads1detailafv110_bk), 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(group_neutralize(close, anl4_ads1detailafv110_bk), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(group_neutralize(close, anl4_ads1detailafv110_bk), 252))'},
    # anl4_ads1detailafv110_estvalue
    # The raw analyst estimation value represents expectations; tracking its momentum relative to price trends identifies divergence.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(anl4_ads1detailafv110_estvalue, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(anl4_ads1detailafv110_estvalue, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(anl4_ads1detailafv110_estvalue, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(anl4_ads1detailafv110_estvalue, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(anl4_ads1detailafv110_estvalue, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(anl4_ads1detailafv110_estvalue, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(anl4_ads1detailafv110_estvalue, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(anl4_ads1detailafv110_estvalue, 252))'},
    # anl4_ads1detailafv110_person
    # Grouping by analyst ID controls for individual analyst coverage style and systematic biases in their stock recommendations.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(group_neutralize(close, anl4_ads1detailafv110_person), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(group_neutralize(close, anl4_ads1detailafv110_person), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(group_neutralize(close, anl4_ads1detailafv110_person), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(group_neutralize(close, anl4_ads1detailafv110_person), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(group_neutralize(close, anl4_ads1detailafv110_person), 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(group_neutralize(close, anl4_ads1detailafv110_person), 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(group_neutralize(close, anl4_ads1detailafv110_person), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(group_neutralize(close, anl4_ads1detailafv110_person), 252))'},
    # anl4_ads1detailafv110_prevval
    # Comparing the previous estimate to the current estimate captures the direction of analyst revisions, a powerful predictor of future returns.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(anl4_ads1detailafv110_prevval, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(anl4_ads1detailafv110_prevval, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(anl4_ads1detailafv110_prevval, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(anl4_ads1detailafv110_prevval, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(anl4_ads1detailafv110_prevval, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(anl4_ads1detailafv110_prevval, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(anl4_ads1detailafv110_prevval, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(anl4_ads1detailafv110_prevval, 252))'},
    # anl4_ads1detailqfv110_bk
    # Broker identity changes can capture shifts in institutional coverage and analyst sentiment.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(anl4_ads1detailqfv110_bk, 126))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(anl4_ads1detailqfv110_bk, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(anl4_ads1detailqfv110_bk, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(anl4_ads1detailqfv110_bk, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(anl4_ads1detailqfv110_bk, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(anl4_ads1detailqfv110_bk, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(anl4_ads1detailqfv110_bk, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(anl4_ads1detailqfv110_bk, 252))'},
    # anl4_ads1detailqfv110_estvalue
    # The consensus analyst estimation value acts as a strong fundamental anchor for stock valuation.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(anl4_ads1detailqfv110_estvalue, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(anl4_ads1detailqfv110_estvalue, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(anl4_ads1detailqfv110_estvalue, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(anl4_ads1detailqfv110_estvalue, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(anl4_ads1detailqfv110_estvalue, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(anl4_ads1detailqfv110_estvalue, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(anl4_ads1detailqfv110_estvalue, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(anl4_ads1detailqfv110_estvalue, 252))'},
    # anl4_ads1detailqfv110_person
    # Analyst-specific ID changes help track individual analyst coverage transitions and revisions.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(anl4_ads1detailqfv110_person, 63))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(anl4_ads1detailqfv110_person, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(anl4_ads1detailqfv110_person, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(anl4_ads1detailqfv110_person, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(anl4_ads1detailqfv110_person, 126)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(anl4_ads1detailqfv110_person, 126)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(anl4_ads1detailqfv110_person, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(anl4_ads1detailqfv110_person, 252))'},
    # anl4_ads1detailqfv110_prevval
    # The previous estimation value serves as the baseline to measure the magnitude of recent analyst revisions.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(anl4_ads1detailqfv110_prevval, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(anl4_ads1detailqfv110_prevval, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(anl4_ads1detailqfv110_prevval, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(anl4_ads1detailqfv110_prevval, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(anl4_ads1detailqfv110_prevval, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(anl4_ads1detailqfv110_prevval, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(anl4_ads1detailqfv110_prevval, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(anl4_ads1detailqfv110_prevval, 252))'},
    # anl4_adxqfv110_down
    # The number of downward revisions indicates deteriorating analyst consensus, acting as a strong negative momentum signal.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(anl4_adxqfv110_down, 63))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(anl4_adxqfv110_down, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(anl4_adxqfv110_down, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(anl4_adxqfv110_down, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(anl4_adxqfv110_down, 126)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(anl4_adxqfv110_down, 126)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(anl4_adxqfv110_down, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(anl4_adxqfv110_down, 252))'},
]

print(f"Total expressions queued: {len(DATA)}")
print("  Batch: llm_analyst_0603_2337 | 20 fields")
print(f"  Estimated runtime: ~{len(DATA)*1.5:.0f} min")
