# parameters_flip_agent_20260514_223639_20260515_011101.py
# Auto-generated by agent.py — flipped expressions (rank instead of -rank)
# These had sharpe ≤ -0.8 — strong inverted signal, flip direction
# Run: cp parameters_flip_agent_20260514_223639_20260515_011101.py parameters.py && python3 main.py

from commands import *
BATCH_NAME = 'flip_agent_20260514_223639'

BASE = {'neutralization': 'SUBINDUSTRY', 'decay': 6, 'truncation': 0.08,
        'delay': 1, 'region': 'USA', 'universe': 'TOP3000'}
B500 = {**BASE, 'universe': 'TOP500'}

DATA = [
    {**BASE, 'code': 'rank(ts_rank(mdl177_valueanalystmodel_qva_chgacc,252))'},
    {**B500, 'code': 'rank(ts_rank(mdl177_valueanalystmodel_qva_chgacc,252))'},
]
print(f"Total expressions queued: {len(DATA)}")
print("  Flip batch: 1 inverted signal(s)")
print(f"Estimated runtime: ~{len(DATA)*1.5:.0f} min")
