# parameters_llm_fundamental_0605_2242.py
# Auto-generated by llm_alpha_generator.py — 20260605_224226
# Model: gemini-3.5-flash | Fields: 20 | Expressions: 160 (incl. auto-TOP200 pairs)
# Run: cp parameters_llm_fundamental_0605_2242.py parameters.py && python3 main.py

from commands import *
BATCH_NAME = 'llm_fundamental_0605_2242'

BASE = {'neutralization': 'SUBINDUSTRY', 'decay': 6, 'truncation': 0.08, 'delay': 1, 'region': 'USA', 'universe': 'TOP3000'}
B500 = {**BASE, 'universe': 'TOP500'}
B200 = {**BASE, 'universe': 'TOP200'}
UNIV = {'TOP3000': BASE, 'TOP500': B500, 'TOP200': B200}

DATA = [
    # accumulated_depreciation_depletion_amortization_ppne
    # High accumulated depreciation suggests aging property, plant, and equipment, potentially signaling future capital expenditure drag.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(accumulated_depreciation_depletion_amortization_ppne, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(accumulated_depreciation_depletion_amortization_ppne, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(accumulated_depreciation_depletion_amortization_ppne, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(accumulated_depreciation_depletion_amortization_ppne, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(accumulated_depreciation_depletion_amortization_ppne, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(accumulated_depreciation_depletion_amortization_ppne, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(accumulated_depreciation_depletion_amortization_ppne, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(accumulated_depreciation_depletion_amortization_ppne, 252))'},
    # acquisition_total_purchase_price
    # Large acquisition outlays can lead to integration risks and goodwill impairment, often resulting in short-to-medium term underperformance.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquisition_total_purchase_price, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquisition_total_purchase_price, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquisition_total_purchase_price, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquisition_total_purchase_price, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquisition_total_purchase_price, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquisition_total_purchase_price, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquisition_total_purchase_price, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquisition_total_purchase_price, 252))'},
    # acquisition_total_purchase_value
    # Total purchase value tracks M&A intensity; aggressive acquiring behavior often correlates with stock underperformance due to premium overpayment.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquisition_total_purchase_value, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquisition_total_purchase_value, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquisition_total_purchase_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquisition_total_purchase_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquisition_total_purchase_value, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquisition_total_purchase_value, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquisition_total_purchase_value, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquisition_total_purchase_value, 252))'},
    # actual_return_on_pension_plan_assets
    # Strong performance in pension plan assets reduces a company's future funding obligations, freeing up cash flow for shareholders.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(actual_return_on_pension_plan_assets, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(actual_return_on_pension_plan_assets, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(actual_return_on_pension_plan_assets, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(actual_return_on_pension_plan_assets, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(actual_return_on_pension_plan_assets, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(actual_return_on_pension_plan_assets, 252)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(actual_return_on_pension_plan_assets, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(actual_return_on_pension_plan_assets, 252))'},
    # afss_accumulated_oci_adjustment_net_tax
    # Unrealized gains or losses in available-for-sale securities reflect the underlying health of the firm's non-core investment portfolio.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(afss_accumulated_oci_adjustment_net_tax, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(afss_accumulated_oci_adjustment_net_tax, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(afss_accumulated_oci_adjustment_net_tax, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(afss_accumulated_oci_adjustment_net_tax, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(afss_accumulated_oci_adjustment_net_tax, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(afss_accumulated_oci_adjustment_net_tax, 252)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(afss_accumulated_oci_adjustment_net_tax, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(afss_accumulated_oci_adjustment_net_tax, 252))'},
    # allocated_sbp_expense_rsu
    # Heavy reliance on restricted stock units for compensation can lead to shareholder dilution and signals high non-cash operating expenses.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(allocated_sbp_expense_rsu, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(allocated_sbp_expense_rsu, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(allocated_sbp_expense_rsu, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(allocated_sbp_expense_rsu, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(allocated_sbp_expense_rsu, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(allocated_sbp_expense_rsu, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(allocated_sbp_expense_rsu, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(allocated_sbp_expense_rsu, 252))'},
    # allocated_sbp_expense_stock_options
    # Stock option expenses reflect dilutive incentive structures that may depress earnings quality and future earnings per share.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(allocated_sbp_expense_stock_options, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(allocated_sbp_expense_stock_options, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(allocated_sbp_expense_stock_options, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(allocated_sbp_expense_stock_options, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(allocated_sbp_expense_stock_options, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(allocated_sbp_expense_stock_options, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(allocated_sbp_expense_stock_options, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(allocated_sbp_expense_stock_options, 252))'},
    # allocated_sbp_expense_total
    # Total share-based compensation expense serves as a proxy for dilution risk and potential over-compensation of insiders.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(allocated_sbp_expense_total, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(allocated_sbp_expense_total, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(allocated_sbp_expense_total, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(allocated_sbp_expense_total, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(allocated_sbp_expense_total, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(allocated_sbp_expense_total, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(allocated_sbp_expense_total, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(allocated_sbp_expense_total, 252))'},
    # allowance_for_doubtful_accounts_2
    # An increasing reserve for doubtful accounts suggests deterioration in customer credit quality and potential future revenue write-downs.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(allowance_for_doubtful_accounts_2, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(allowance_for_doubtful_accounts_2, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(allowance_for_doubtful_accounts_2, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(allowance_for_doubtful_accounts_2, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(allowance_for_doubtful_accounts_2, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(allowance_for_doubtful_accounts_2, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(allowance_for_doubtful_accounts_2, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(allowance_for_doubtful_accounts_2, 252))'},
    # amortized_cost_available_securities
    # The amortized cost of available-for-sale securities tracks capital tied up in low-yield financial investments rather than core business growth.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(amortized_cost_available_securities, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(amortized_cost_available_securities, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(amortized_cost_available_securities, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(amortized_cost_available_securities, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(amortized_cost_available_securities, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(amortized_cost_available_securities, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(amortized_cost_available_securities, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(amortized_cost_available_securities, 252))'},
    # annual_deferred_income_tax_expense
    # Rising deferred tax expenses can indicate temporary book-tax differences that may lead to lower cash flows in future periods.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(annual_deferred_income_tax_expense, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(annual_deferred_income_tax_expense, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(annual_deferred_income_tax_expense, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(annual_deferred_income_tax_expense, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(annual_deferred_income_tax_expense, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(annual_deferred_income_tax_expense, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(annual_deferred_income_tax_expense, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(annual_deferred_income_tax_expense, 252))'},
    # annual_intangible_amortization_expense_second_year
    # Amortization profiles of intangible assets impact future GAAP earnings; high upcoming amortization acts as a systematic headwind to net income.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(annual_intangible_amortization_expense_second_year, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(annual_intangible_amortization_expense_second_year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(annual_intangible_amortization_expense_second_year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(annual_intangible_amortization_expense_second_year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(annual_intangible_amortization_expense_second_year, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(annual_intangible_amortization_expense_second_year, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(annual_intangible_amortization_expense_second_year, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(annual_intangible_amortization_expense_second_year, 252))'},
    # annual_intangible_assets_net_carrying_value
    # A high concentration of intangible assets relative to tangible ones can indicate lower asset quality and higher risk of future impairment charges.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(annual_intangible_assets_net_carrying_value, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(annual_intangible_assets_net_carrying_value, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(annual_intangible_assets_net_carrying_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(annual_intangible_assets_net_carrying_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(annual_intangible_assets_net_carrying_value, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(annual_intangible_assets_net_carrying_value, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(annual_intangible_assets_net_carrying_value, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(annual_intangible_assets_net_carrying_value, 252))'},
    # antidilutive_securities_eps_exclusion_count
    # A high count of excluded antidilutive securities indicates complex capital structures with latent dilution risk if stock price rises.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(antidilutive_securities_eps_exclusion_count, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(antidilutive_securities_eps_exclusion_count, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(antidilutive_securities_eps_exclusion_count, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(antidilutive_securities_eps_exclusion_count, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(antidilutive_securities_eps_exclusion_count, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(antidilutive_securities_eps_exclusion_count, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(antidilutive_securities_eps_exclusion_count, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(antidilutive_securities_eps_exclusion_count, 252))'},
    # antidilutive_securities_excluded_eps
    # An increase in excluded antidilutive options/warrants can indicate depressed current stock prices relative to historical strike prices.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(antidilutive_securities_excluded_eps, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(antidilutive_securities_excluded_eps, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(antidilutive_securities_excluded_eps, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(antidilutive_securities_excluded_eps, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(antidilutive_securities_excluded_eps, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(antidilutive_securities_excluded_eps, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(antidilutive_securities_excluded_eps, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(antidilutive_securities_excluded_eps, 252))'},
    # antidilutive_stock_options_excluded_eps
    # An increase in antidilutive options excluded from EPS often reflects underlying stock price depreciation or high potential dilution, signaling negative momentum.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(antidilutive_stock_options_excluded_eps, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(antidilutive_stock_options_excluded_eps, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(antidilutive_stock_options_excluded_eps, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(antidilutive_stock_options_excluded_eps, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(antidilutive_stock_options_excluded_eps, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(antidilutive_stock_options_excluded_eps, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(antidilutive_stock_options_excluded_eps, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(antidilutive_stock_options_excluded_eps, 252))'},
    # antidilutive_stock_options_excluded_eps_2
    # Tracking the change in excluded antidilutive stock options helps identify shifts in option overhang and dilution risk.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(antidilutive_stock_options_excluded_eps_2, 126))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(antidilutive_stock_options_excluded_eps_2, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(antidilutive_stock_options_excluded_eps_2, 10) * rank(ts_delta(close, 10)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(antidilutive_stock_options_excluded_eps_2, 10) * rank(ts_delta(close, 10)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(antidilutive_stock_options_excluded_eps_2, 126)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(antidilutive_stock_options_excluded_eps_2, 126)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(antidilutive_stock_options_excluded_eps_2, 126))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(antidilutive_stock_options_excluded_eps_2, 126))'},
    # assets
    # The asset growth anomaly suggests that firms aggressively expanding their balance sheets tend to underperform their peers.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(assets, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(assets, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(assets, 42) * rank(ts_delta(close, 10)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(assets, 42) * rank(ts_delta(close, 10)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(assets, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(assets, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(assets, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(assets, 252))'},
    # assets_curr
    # Slowing current asset growth can indicate tightening liquidity or working capital optimization, which correlates with future stock performance.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(assets_curr, 180))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(assets_curr, 180))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(assets_curr, 15) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(assets_curr, 15) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(assets_curr, 180)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(assets_curr, 180)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(assets_curr, 180))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(assets_curr, 180))'},
    # assets_fair_value_lvl1
    # A higher proportion of level 1 fair value assets indicates greater liquidity and balance sheet transparency, reducing risk premium.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(assets_fair_value_lvl1, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(assets_fair_value_lvl1, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(assets_fair_value_lvl1, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(assets_fair_value_lvl1, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(assets_fair_value_lvl1, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(assets_fair_value_lvl1, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(assets_fair_value_lvl1, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(assets_fair_value_lvl1, 252))'},
]

print(f"Total expressions queued: {len(DATA)}")
print("  Batch: llm_fundamental_0605_2242 | 20 fields")
print(f"  Estimated runtime: ~{len(DATA)*1.5:.0f} min")
