# parameters_llm_fundamental_0622_0957.py
# Auto-generated by llm_alpha_generator.py — 20260622_095701
# Model: gemini-3.5-flash | Fields: 1 | Expressions: 12 (incl. auto-TOP200 pairs)
# Run: cp parameters_llm_fundamental_0622_0957.py parameters.py && python3 main.py

from commands import *
BATCH_NAME = 'llm_fundamental_0622_0957'

BASE = {'neutralization': 'INDUSTRY', 'decay': 6, 'truncation': 0.08, 'delay': 1, 'region': 'USA', 'universe': 'TOP3000'}
B500 = {**BASE, 'universe': 'TOP500'}
B200 = {**BASE, 'universe': 'TOP200'}
UNIV = {'TOP3000': BASE, 'TOP500': B500, 'TOP200': B200}

DATA = [
    # fn_def_income_tax_expense_a
    # Deferred income tax expense captures changes in future tax liabilities; normalizing by market capitalization or ranking within industry isolates tax-planning efficiency relative to size and peers.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(fn_def_income_tax_expense_a, 252), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(fn_def_income_tax_expense_a, 252), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(ts_backfill(fn_def_income_tax_expense_a, 252), 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(ts_backfill(fn_def_income_tax_expense_a, 252), 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(fn_def_income_tax_expense_a, 126) / cap, 126))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(fn_def_income_tax_expense_a, 126) / cap, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_rank(ts_backfill(fn_def_income_tax_expense_a, 252), 252), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_rank(ts_backfill(fn_def_income_tax_expense_a, 252), 252), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(ts_backfill(fn_def_income_tax_expense_a, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(ts_backfill(fn_def_income_tax_expense_a, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(ts_backfill(fn_def_income_tax_expense_a, 252) / cap, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(ts_backfill(fn_def_income_tax_expense_a, 252) / cap, 252)))'},
]

print(f"Total expressions queued: {len(DATA)}")
print("  Batch: llm_fundamental_0622_0957 | 1 fields")
print(f"  Estimated runtime: ~{len(DATA)*1.5:.0f} min")
