# parameters_llm_fundamental_0605_2257.py
# Auto-generated by llm_alpha_generator.py — 20260605_225741
# Model: gemini-3.5-flash | Fields: 20 | Expressions: 160 (incl. auto-TOP200 pairs)
# Run: cp parameters_llm_fundamental_0605_2257.py parameters.py && python3 main.py

from commands import *
BATCH_NAME = 'llm_fundamental_0605_2257'

BASE = {'neutralization': 'SUBINDUSTRY', 'decay': 6, 'truncation': 0.08, 'delay': 1, 'region': 'USA', 'universe': 'TOP3000'}
B500 = {**BASE, 'universe': 'TOP500'}
B200 = {**BASE, 'universe': 'TOP200'}
UNIV = {'TOP3000': BASE, 'TOP500': B500, 'TOP200': B200}

DATA = [
    # accumulated_depreciation_depletion_amortization_ppne
    # Higher accumulated depreciation relative to peers indicates an aging asset base or heavy capital intensity, which acts as a negative quality signal.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(accumulated_depreciation_depletion_amortization_ppne, 120), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(accumulated_depreciation_depletion_amortization_ppne, 120), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(accumulated_depreciation_depletion_amortization_ppne, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(accumulated_depreciation_depletion_amortization_ppne, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_rank(accumulated_depreciation_depletion_amortization_ppne, 63), subindustry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_rank(accumulated_depreciation_depletion_amortization_ppne, 63), subindustry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_zscore(accumulated_depreciation_depletion_amortization_ppne, 63), 10) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_zscore(accumulated_depreciation_depletion_amortization_ppne, 63), 10) * rank(ts_delta(close, 5)))'},
    # acquisition_total_purchase_price
    # Large acquisition outlays often lead to short-term integration risks and cash drains; backfilling handles sparse transaction data.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(acquisition_total_purchase_price, 252), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(acquisition_total_purchase_price, 252), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_backfill(acquisition_total_purchase_price, 120), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_backfill(acquisition_total_purchase_price, 120), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_std_dev(ts_backfill(acquisition_total_purchase_price, 120), 126))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_std_dev(ts_backfill(acquisition_total_purchase_price, 120), 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_zscore(ts_backfill(acquisition_total_purchase_price, 252), 252), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_zscore(ts_backfill(acquisition_total_purchase_price, 252), 252), industry))'},
    # acquisition_total_purchase_value
    # Total purchase value of acquisitions measures capital allocation aggressiveness, where high values often lead to post-merger underperformance.
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(ts_backfill(acquisition_total_purchase_value, 252), 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(ts_backfill(acquisition_total_purchase_value, 252), 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(ts_backfill(acquisition_total_purchase_value, 120), 21), 63))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_delta(ts_backfill(acquisition_total_purchase_value, 120), 21), 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_corr(ts_backfill(acquisition_total_purchase_value, 120), close, 126))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_corr(ts_backfill(acquisition_total_purchase_value, 120), close, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(winsorize(ts_backfill(acquisition_total_purchase_value, 252), std=4), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(winsorize(ts_backfill(acquisition_total_purchase_value, 252), std=4), 252))'},
    # actual_return_on_pension_plan_assets
    # Strong pension asset returns reduce corporate funding liabilities, freeing up future cash flows for productive use.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(actual_return_on_pension_plan_assets, 252), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(actual_return_on_pension_plan_assets, 252), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(ts_backfill(actual_return_on_pension_plan_assets, 120), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(ts_backfill(actual_return_on_pension_plan_assets, 120), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_rank(ts_backfill(actual_return_on_pension_plan_assets, 120), 63), sector))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_rank(ts_backfill(actual_return_on_pension_plan_assets, 120), 63), sector))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_backfill(actual_return_on_pension_plan_assets, 63), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_backfill(actual_return_on_pension_plan_assets, 63), 21) * rank(ts_delta(close, 5)))'},
    # afss_accumulated_oci_adjustment_net_tax
    # OCI adjustments reflect unrealized gains/losses on securities, serving as a leading indicator of balance sheet health.
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(winsorize(ts_backfill(afss_accumulated_oci_adjustment_net_tax, 252), std=4), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(winsorize(ts_backfill(afss_accumulated_oci_adjustment_net_tax, 252), std=4), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(ts_backfill(afss_accumulated_oci_adjustment_net_tax, 120), 21), 126))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_delta(ts_backfill(afss_accumulated_oci_adjustment_net_tax, 120), 21), 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(ts_backfill(afss_accumulated_oci_adjustment_net_tax, 252), 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(ts_backfill(afss_accumulated_oci_adjustment_net_tax, 252), 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_corr(ts_backfill(afss_accumulated_oci_adjustment_net_tax, 120), returns, 22), 126))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_corr(ts_backfill(afss_accumulated_oci_adjustment_net_tax, 120), returns, 22), 126))'},
    # allocated_sbp_expense_rsu
    # Elevated RSU expenses increase share dilution and represent a high cost of compensation, dragging down shareholder returns.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(allocated_sbp_expense_rsu, 120), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(allocated_sbp_expense_rsu, 120), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_backfill(allocated_sbp_expense_rsu, 63), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_backfill(allocated_sbp_expense_rsu, 63), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_zscore(ts_backfill(allocated_sbp_expense_rsu, 120), 252), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_zscore(ts_backfill(allocated_sbp_expense_rsu, 120), 252), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(ts_backfill(allocated_sbp_expense_rsu, 120), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(ts_backfill(allocated_sbp_expense_rsu, 120), ts_step(1), 252, rettype=2))'},
    # allocated_sbp_expense_stock_options
    # Stock option compensation expenses signal potential future dilution and high management compensation costs.
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(winsorize(ts_backfill(allocated_sbp_expense_stock_options, 120), std=4), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(winsorize(ts_backfill(allocated_sbp_expense_stock_options, 120), std=4), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_std_dev(ts_backfill(allocated_sbp_expense_stock_options, 63), 22), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_std_dev(ts_backfill(allocated_sbp_expense_stock_options, 63), 22), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(ts_backfill(allocated_sbp_expense_stock_options, 120), 21), 63))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_delta(ts_backfill(allocated_sbp_expense_stock_options, 120), 21), 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_rank(ts_backfill(allocated_sbp_expense_stock_options, 120), 63), subindustry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_rank(ts_backfill(allocated_sbp_expense_stock_options, 120), 63), subindustry))'},
    # allocated_sbp_expense_total
    # Total share-based compensation is a major source of shareholder dilution; tracking its trend reveals capital discipline.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(allocated_sbp_expense_total, 120), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(allocated_sbp_expense_total, 120), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_backfill(allocated_sbp_expense_total, 63), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_backfill(allocated_sbp_expense_total, 63), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(ts_backfill(allocated_sbp_expense_total, 120), 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(ts_backfill(allocated_sbp_expense_total, 120), 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(ts_backfill(allocated_sbp_expense_total, 120), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(ts_backfill(allocated_sbp_expense_total, 120), ts_step(1), 252, rettype=2))'},
    # allowance_for_doubtful_accounts_2
    # An increase in reserves for doubtful accounts signals deteriorating customer credit quality; group-relative transformations are optimized for the TOP200 universe to limit self-correlation.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(allowance_for_doubtful_accounts_2, 252), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(allowance_for_doubtful_accounts_2, 252), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_rank(allowance_for_doubtful_accounts_2, 126), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_rank(allowance_for_doubtful_accounts_2, 126), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(allowance_for_doubtful_accounts_2, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(allowance_for_doubtful_accounts_2, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(allowance_for_doubtful_accounts_2, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(allowance_for_doubtful_accounts_2, 21) * rank(ts_delta(close, 5)))'},
    # amortized_cost_available_securities
    # Amortized cost of available-for-sale securities reflects conservative asset backing, with sector-group ranking proving highly effective for financial firms in the TOP200.
    {**UNIV['TOP3000'], 'code': 'rank(group_rank(ts_zscore(ts_backfill(amortized_cost_available_securities, 252), 252), sector))'},
    {**UNIV['TOP200'], 'code': 'rank(group_rank(ts_zscore(ts_backfill(amortized_cost_available_securities, 252), 252), sector))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_std_dev(ts_backfill(amortized_cost_available_securities, 126), 63))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_std_dev(ts_backfill(amortized_cost_available_securities, 126), 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(amortized_cost_available_securities, 252), 0.05))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(amortized_cost_available_securities, 252), 0.05))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(ts_backfill(amortized_cost_available_securities, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(ts_backfill(amortized_cost_available_securities, 252), ts_step(1), 252, rettype=2))'},
    # annual_deferred_income_tax_expense
    # Deferred tax expenses highlight differences between book and tax accounting, where winsorization mitigates extreme values in sparse annual disclosures.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(annual_deferred_income_tax_expense, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(annual_deferred_income_tax_expense, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_rank(annual_deferred_income_tax_expense, 252), subindustry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_rank(annual_deferred_income_tax_expense, 252), subindustry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_zscore(annual_deferred_income_tax_expense, 126), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_zscore(annual_deferred_income_tax_expense, 126), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(winsorize(annual_deferred_income_tax_expense, std=4), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(winsorize(annual_deferred_income_tax_expense, std=4), 252))'},
    # annual_intangible_amortization_expense_second_year
    # Projected amortization expenses capture future asset depreciation trends, and cross-sectional industry ranking isolates asset-light outperformance.
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(ts_backfill(annual_intangible_amortization_expense_second_year, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(ts_backfill(annual_intangible_amortization_expense_second_year, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_rank(annual_intangible_amortization_expense_second_year, 252), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_rank(annual_intangible_amortization_expense_second_year, 252), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(annual_intangible_amortization_expense_second_year, 120), 63))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(annual_intangible_amortization_expense_second_year, 120), 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_zscore(annual_intangible_amortization_expense_second_year, 252), 10) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_zscore(annual_intangible_amortization_expense_second_year, 252), 10) * rank(ts_delta(close, 5)))'},
    # annual_intangible_assets_net_carrying_value
    # Carrying value of intangible assets represents potential balance sheet bloat; tracking its correlation with stock price identifies overvalued firms.
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(annual_intangible_assets_net_carrying_value, 252), 0.02))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(annual_intangible_assets_net_carrying_value, 252), 0.02))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_corr(annual_intangible_assets_net_carrying_value, close, 126))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_corr(annual_intangible_assets_net_carrying_value, close, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_rank(annual_intangible_assets_net_carrying_value, 252), sector))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_rank(annual_intangible_assets_net_carrying_value, 252), sector))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(winsorize(ts_backfill(annual_intangible_assets_net_carrying_value, 252), std=4), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(winsorize(ts_backfill(annual_intangible_assets_net_carrying_value, 252), std=4), 252))'},
    # antidilutive_securities_eps_exclusion_count
    # A high count of excluded antidilutive securities indicates potential structural overhang and complex capital structures, yielding strong signals in liquid TOP200 names.
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(ts_backfill(antidilutive_securities_eps_exclusion_count, 252), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(ts_backfill(antidilutive_securities_eps_exclusion_count, 252), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_rank(antidilutive_securities_eps_exclusion_count, 252), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_rank(antidilutive_securities_eps_exclusion_count, 252), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(antidilutive_securities_eps_exclusion_count, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(antidilutive_securities_eps_exclusion_count, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(antidilutive_securities_eps_exclusion_count, 63))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(antidilutive_securities_eps_exclusion_count, 63))'},
    # antidilutive_securities_excluded_eps
    # The exclusion of antidilutive securities impacts adjusted EPS metrics, and its trend slope helps identify firms with improving capital efficiency.
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(ts_backfill(antidilutive_securities_excluded_eps, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(ts_backfill(antidilutive_securities_excluded_eps, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_corr(antidilutive_securities_excluded_eps, returns, 63), 126))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_corr(antidilutive_securities_excluded_eps, returns, 63), 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_rank(antidilutive_securities_excluded_eps, 252), subindustry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_rank(antidilutive_securities_excluded_eps, 252), subindustry))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(antidilutive_securities_excluded_eps, 252), 0.01))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(antidilutive_securities_excluded_eps, 252), 0.01))'},
    # antidilutive_stock_options_excluded_eps
    # Excluded stock options reflect underlying employee compensation dilution risk; combining this with momentum isolates high-quality growth companies.
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(winsorize(ts_backfill(antidilutive_stock_options_excluded_eps, 252), std=4), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(winsorize(ts_backfill(antidilutive_stock_options_excluded_eps, 252), std=4), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_zscore(antidilutive_stock_options_excluded_eps, 252), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_zscore(antidilutive_stock_options_excluded_eps, 252), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_rank(antidilutive_stock_options_excluded_eps, 126), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_rank(antidilutive_stock_options_excluded_eps, 126), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_std_dev(ts_backfill(antidilutive_stock_options_excluded_eps, 120), 63))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_std_dev(ts_backfill(antidilutive_stock_options_excluded_eps, 120), 63))'},
    # antidilutive_stock_options_excluded_eps_2
    # Antidilutive options represent out-of-the-money potential dilution; a high count often indicates depressed stock prices relative to historical option strike levels.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(antidilutive_stock_options_excluded_eps_2, 120), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(antidilutive_stock_options_excluded_eps_2, 120), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_backfill(antidilutive_stock_options_excluded_eps_2, 120), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_backfill(antidilutive_stock_options_excluded_eps_2, 120), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_rank(ts_backfill(antidilutive_stock_options_excluded_eps_2, 120), 63), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_rank(ts_backfill(antidilutive_stock_options_excluded_eps_2, 120), 63), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(ts_backfill(antidilutive_stock_options_excluded_eps_2, 120), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(ts_backfill(antidilutive_stock_options_excluded_eps_2, 120), ts_step(1), 252, rettype=2))'},
    # assets
    # Exploits the classic asset growth anomaly where firms with rapid asset expansion tend to underperform their peers due to empire-building or overinvestment.
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_backfill(assets, 120), 252) / ts_delay(ts_backfill(assets, 120), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_delta(ts_backfill(assets, 120), 252) / ts_delay(ts_backfill(assets, 120), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_backfill(assets, 120), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_backfill(assets, 120), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_zscore(ts_backfill(assets, 120), 252), sector))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_zscore(ts_backfill(assets, 120), 252), sector))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(ts_backfill(assets, 120), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(ts_backfill(assets, 120), ts_step(1), 252, rettype=2))'},
    # assets_curr
    # Measures short-term liquidity expansion; group-relative current asset growth in the TOP200 universe identifies firms managing working capital efficiently without bloating balance sheets.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(assets_curr, 120), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(assets_curr, 120), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(ts_backfill(assets_curr, 120), 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(ts_backfill(assets_curr, 120), 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_rank(ts_backfill(assets_curr, 120), 63), subindustry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_rank(ts_backfill(assets_curr, 120), 63), subindustry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_zscore(ts_backfill(assets_curr, 120), 63), 10) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_zscore(ts_backfill(assets_curr, 120), 63), 10) * rank(ts_delta(close, 5)))'},
    # assets_fair_value_lvl1
    # Level 1 assets are highly liquid and mark-to-market; changes in their level signal shifts in highly reliable, low-valuation-risk balance sheet liquidity.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(assets_fair_value_lvl1, 120), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(assets_fair_value_lvl1, 120), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_backfill(assets_fair_value_lvl1, 120), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_backfill(assets_fair_value_lvl1, 120), 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_zscore(ts_backfill(assets_fair_value_lvl1, 120), 252), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_zscore(ts_backfill(assets_fair_value_lvl1, 120), 252), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(ts_backfill(assets_fair_value_lvl1, 120), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(ts_backfill(assets_fair_value_lvl1, 120), ts_step(1), 252, rettype=2))'},
]

print(f"Total expressions queued: {len(DATA)}")
print("  Batch: llm_fundamental_0605_2257 | 20 fields")
print(f"  Estimated runtime: ~{len(DATA)*1.5:.0f} min")
