# parameters_llm_analyst_0604_0734.py
# Auto-generated by llm_alpha_generator.py — 20260604_073425
# Model: gemini-3.5-flash | Fields: 20 | Expressions: 145 (incl. auto-TOP200 pairs)
# Run: cp parameters_llm_analyst_0604_0734.py parameters.py && python3 main.py

from commands import *
BATCH_NAME = 'llm_analyst_0604_0734'

BASE = {'neutralization': 'SUBINDUSTRY', 'decay': 6, 'truncation': 0.08, 'delay': 1, 'region': 'USA', 'universe': 'TOP3000'}
B500 = {**BASE, 'universe': 'TOP500'}
B200 = {**BASE, 'universe': 'TOP200'}
UNIV = {'TOP3000': BASE, 'TOP500': B500, 'TOP200': B200}

DATA = [
    # anl4_ady_down
    # An increase in downward analyst revisions indicates deteriorating sentiment and predicts near-term price underperformance.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(anl4_ady_down, 63))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(anl4_ady_down, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(anl4_ady_down, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(anl4_ady_down, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(anl4_ady_down, 126)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(anl4_ady_down, 126)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(anl4_ady_down, 63)) /* TOP200 */'},
    # anl4_ady_high
    # An increase in the maximum analyst estimate reflects growing optimistic consensus and potential upward price momentum.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(anl4_ady_high, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(anl4_ady_high, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(anl4_ady_high, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(anl4_ady_high, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(anl4_ady_high, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(anl4_ady_high, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(anl4_ady_high, 252)) /* TOP200 */'},
    # anl4_ady_low
    # An upward shift in the lowest analyst estimate raises the valuation floor and reduces downside risk for the stock.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(anl4_ady_low, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(anl4_ady_low, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(anl4_ady_low, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(anl4_ady_low, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(anl4_ady_low, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(anl4_ady_low, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(anl4_ady_low, 252)) /* TOP200 */'},
    # anl4_ady_mean
    # The consensus mean of analyst estimates acts as a reliable expectation benchmark that drives institutional capital flows.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(anl4_ady_mean, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(anl4_ady_mean, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(anl4_ady_mean, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(anl4_ady_mean, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(anl4_ady_mean, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(anl4_ady_mean, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(anl4_ady_mean, 252)) /* TOP200 */'},
    # anl4_ady_median
    # The median analyst estimate provides a robust consensus measure that is less sensitive to extreme outlier forecasts.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(anl4_ady_median, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(anl4_ady_median, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(anl4_ady_median, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(anl4_ady_median, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(anl4_ady_median, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(anl4_ady_median, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(anl4_ady_median, 252)) /* TOP200 */'},
    # anl4_ady_numest
    # A rising number of forecasting analysts indicates increasing institutional interest and improved information efficiency.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(anl4_ady_numest, 126))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(anl4_ady_numest, 126))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(anl4_ady_numest, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(anl4_ady_numest, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(anl4_ady_numest, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(anl4_ady_numest, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(anl4_ady_numest, 126)) /* TOP200 */'},
    # anl4_ady_pu
    # An increase in upward analyst revisions signals strong positive fundamental momentum and upcoming earnings surprises.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(anl4_ady_pu, 63))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(anl4_ady_pu, 63))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(anl4_ady_pu, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(anl4_ady_pu, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(anl4_ady_pu, 126)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(anl4_ady_pu, 126)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(anl4_ady_pu, 63)) /* TOP200 */'},
    # anl4_af_cfps_value
    # Actual cash flow per share is a primary metric of intrinsic corporate value and earnings quality.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(anl4_af_cfps_value, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(anl4_af_cfps_value, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(anl4_af_cfps_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(anl4_af_cfps_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(anl4_af_cfps_value, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(anl4_af_cfps_value, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(anl4_af_cfps_value, 252)) /* TOP200 */'},
    # anl4_af_div_value
    # Announced dividend values signal management's confidence in long-term earnings stability and return of capital.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(anl4_af_div_value, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(anl4_af_div_value, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(anl4_af_div_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(anl4_af_div_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(anl4_af_div_value, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(anl4_af_div_value, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(anl4_af_div_value, 252)) /* TOP200 */'},
    # anl4_af_eps_value
    # Actual earnings per share growth acts as the ultimate long-term driver of equity valuation and investor returns.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(anl4_af_eps_value, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(anl4_af_eps_value, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(anl4_af_eps_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(anl4_af_eps_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(anl4_af_eps_value, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(anl4_af_eps_value, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(anl4_af_eps_value, 252)) /* TOP200 */'},
    # anl4_afv4_actual
    # Announced financial data points represent hard fundamental releases that resolve market uncertainty and reset valuations.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(anl4_afv4_actual, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(anl4_afv4_actual, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(anl4_afv4_actual, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(anl4_afv4_actual, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(anl4_afv4_actual, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(anl4_afv4_actual, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(anl4_afv4_actual, 252)) /* TOP200 */'},
    # anl4_afv4_cfps_high
    # The highest forecast for annual cash flow per share identifies companies with the strongest potential upside scenarios.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(anl4_afv4_cfps_high, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(anl4_afv4_cfps_high, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(anl4_afv4_cfps_high, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(anl4_afv4_cfps_high, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(anl4_afv4_cfps_high, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(anl4_afv4_cfps_high, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(anl4_afv4_cfps_high, 252)) /* TOP200 */'},
    # anl4_afv4_cfps_low
    # An increase in the worst-case cash flow per share estimate signals a reduction in fundamental tail risk.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(anl4_afv4_cfps_low, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(anl4_afv4_cfps_low, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(anl4_afv4_cfps_low, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(anl4_afv4_cfps_low, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(anl4_afv4_cfps_low, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(anl4_afv4_cfps_low, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(anl4_afv4_cfps_low, 252)) /* TOP200 */'},
    # anl4_afv4_cfps_mean
    # The average annual cash flow per share estimate represents the consensus expectation of a firm's cash-generating power.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(anl4_afv4_cfps_mean, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(anl4_afv4_cfps_mean, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(anl4_afv4_cfps_mean, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(anl4_afv4_cfps_mean, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(anl4_afv4_cfps_mean, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(anl4_afv4_cfps_mean, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(anl4_afv4_cfps_mean, 252)) /* TOP200 */'},
    # anl4_afv4_cfps_median
    # The median annual cash flow per share estimate filters out extreme forecasts to reveal the true central tendency of analyst expectations.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(anl4_afv4_cfps_median, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(anl4_afv4_cfps_median, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(anl4_afv4_cfps_median, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(anl4_afv4_cfps_median, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(anl4_afv4_cfps_median, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(anl4_afv4_cfps_median, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(anl4_afv4_cfps_median, 252)) /* TOP200 */'},
    # anl4_afv4_cfps_number
    # An increase in the number of analysts estimating cash flow per share indicates rising institutional interest and coverage momentum.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(anl4_afv4_cfps_number, 63))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(anl4_afv4_cfps_number, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(anl4_afv4_cfps_number, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(anl4_afv4_cfps_number, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(anl4_afv4_cfps_number, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(anl4_afv4_cfps_number, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(anl4_afv4_cfps_number, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(anl4_afv4_cfps_number, 252)))'},
    # anl4_afv4_div_high
    # Optimistic upper-bound dividend forecasts reflect strong underlying profitability and management confidence, which can be captured via long-term time-series ranking.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(anl4_afv4_div_high, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(anl4_afv4_div_high, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(anl4_afv4_div_high, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(anl4_afv4_div_high, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(anl4_afv4_div_high, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(anl4_afv4_div_high, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(anl4_afv4_div_high, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(anl4_afv4_div_high, 252)))'},
    # anl4_afv4_div_low
    # The worst-case dividend estimate acts as a conservative floor for yield-seeking investors, and its momentum signals fundamental safety.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(anl4_afv4_div_low, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(anl4_afv4_div_low, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(anl4_afv4_div_low, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(anl4_afv4_div_low, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(anl4_afv4_div_low, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(anl4_afv4_div_low, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(anl4_afv4_div_low, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(anl4_afv4_div_low, 252)))'},
    # anl4_afv4_div_mean
    # Changes in consensus average dividend expectations represent structural shifts in corporate payout policy and value characteristics.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(anl4_afv4_div_mean, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(anl4_afv4_div_mean, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(anl4_afv4_div_mean, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(anl4_afv4_div_mean, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(anl4_afv4_div_mean, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(anl4_afv4_div_mean, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(anl4_afv4_div_mean, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(anl4_afv4_div_mean, 252)))'},
    # anl4_afv4_div_median
    # Median analyst estimates filter out extreme outlier forecasts, providing a robust, noise-free proxy for the market's true dividend expectations.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(anl4_afv4_div_median, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(anl4_afv4_div_median, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(anl4_afv4_div_median, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(anl4_afv4_div_median, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(anl4_afv4_div_median, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(anl4_afv4_div_median, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(anl4_afv4_div_median, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(anl4_afv4_div_median, 252)))'},
]

print(f"Total expressions queued: {len(DATA)}")
print("  Batch: llm_analyst_0604_0734 | 20 fields")
print(f"  Estimated runtime: ~{len(DATA)*1.5:.0f} min")
