# parameters_llm_model_credit_risk_model53_0528_2331.py
# Auto-generated by llm_alpha_generator.py — 20260528_233109
# Model: gemini-3.5-flash | Fields: 30 | Expressions: 120
# Run: cp parameters_llm_model_credit_risk_model53_0528_2331.py parameters.py && python3 main.py

from commands import *
BATCH_NAME = 'llm_model_credit_risk_model53_0528_2331'

BASE = {'neutralization': 'SUBINDUSTRY', 'decay': 6, 'truncation': 0.08, 'delay': 1, 'region': 'USA', 'universe': 'TOP3000'}
B500 = {**BASE, 'universe': 'TOP500'}
B200 = {**BASE, 'universe': 'TOP200'}
UNIV = {'TOP3000': BASE, 'TOP500': B500, 'TOP200': B200}

DATA = [
    # mdl53_implied_ratings
    # Implied credit ratings measure fundamental risk, where short-term lookbacks and price momentum interactions capture rapid shifts in creditworthiness.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_implied_ratings, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_implied_ratings, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_implied_ratings, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_implied_ratings, 126)))'},
    # mdl53_implied_spreads
    # Model-implied credit spreads reflect market-priced default risk, which mean-reverts and interacts strongly with short-term equity momentum.
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_implied_spreads, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_implied_spreads, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_implied_spreads, 10), 10))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_implied_spreads, 63))'},
    # mdl53_jc5_10year
    # Long-term default probabilities are best analyzed relative to short-term horizons to capture yield-curve-like steepness and distress signals.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_10year - mdl53_jc5_1year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_10year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_jc5_1year - mdl53_jc5_10year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_10year, 63))'},
    # mdl53_jc5_1month
    # Ultra-short horizon default probabilities react to immediate liquidity shocks, making acceleration and short lookbacks highly predictive.
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc5_1month, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_1month, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_1year - mdl53_jc5_1month, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_jc5_1month, 126)))'},
    # mdl53_jc5_1year
    # One-year default probability is a standard horizon where z-scoring and default curve spreads reveal systematic credit improvements.
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc5_1year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_5year - mdl53_jc5_1year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_1year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc5_1year, 21), 21))'},
    # mdl53_jc5_2year
    # Two-year default measures capture medium-term business cycle risks, which benefit from curve-spread smoothing and acceleration filters.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_2year - mdl53_jc5_1month, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_2year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_2year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc5_2year, 21), 21))'},
    # mdl53_jc5_3month
    # Three-month default probabilities reflect near-term credit stress, where rapid momentum and curve steepness interactions generate clean signals.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_3month, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_3year - mdl53_jc5_3month, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc5_3month, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_jc5_3month, 126)))'},
    # mdl53_jc5_3year
    # Three-year credit risk acts as a macro-sensitive proxy, suited for z-score normalization and default acceleration capture.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_3year - mdl53_jc5_1year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_3year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc5_3year, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc5_3year, 252))'},
    # mdl53_jc5_4year
    # Four-year default probability changes are leading indicators of structural solvency shifts, captured through curve spreads and price momentum.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_4year - mdl53_jc5_1year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_4year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_4year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc5_4year, 21), 21))'},
    # mdl53_jc5_5year
    # Five-year default risk represents the standard long-term benchmark, where curve inversion signals indicate mean-reverting distress opportunities.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_5year - mdl53_jc5_1year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_5year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_jc5_1year - mdl53_jc5_5year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc5_5year, 252))'},
    # mdl53_jc5_6month
    # Six-month default probability captures semi-annual credit cycles, optimized using decay-weighted curve differentials and short-term ranks.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_6month, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_5year - mdl53_jc5_6month, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc5_6month, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_jc5_6month, 126)))'},
    # mdl53_jc5_7year
    # Seven-year default probabilities provide stable long-term solvency signals that benefit from z-scoring and cross-sectional acceleration metrics.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_7year - mdl53_jc5_1year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_7year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc5_7year, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc5_7year, 252))'},
    # mdl53_jc6_10year
    # The Jarrow-Chava v6 model's 10-year horizon identifies long-term structural distress, best extracted via curve steepness and decay-weighted momentum.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_10year - mdl53_jc6_1year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc6_10year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_10year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc6_10year, 21), 21))'},
    # mdl53_jc6_1month
    # The JC6 1-month horizon is highly sensitive to sudden market shocks, making short-term lookbacks and acceleration filters critical.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_1month, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc6_1year - mdl53_jc6_1month, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc6_1month, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_jc6_1month, 126)))'},
    # mdl53_jc6_1year
    # The JC6 1-year default probability is a robust solvency metric that combines well with price momentum and long-short term spreads.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_10year - mdl53_jc6_1year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc6_1year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc6_1year, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc6_1year, 252))'},
    # mdl53_jc6_2year
    # Medium-term default probability captures credit migration before it is fully priced in by equity markets.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_2year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc6_2year, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_2year - mdl53_jc6_3month, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc6_2year, 126))'},
    # mdl53_jc6_3month
    # Short-term default risk spikes signal acute distress that often mean-reverts or triggers sharp underperformance.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_3month, 63))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_jc6_3month - mdl53_jc6_5year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc6_3month, 10), 10))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc6_3month, 21) * rank(ts_delta(close, 5)))'},
    # mdl53_jc6_3year
    # Three-year default probability acts as a structural credit anchor, filtering out short-term liquidity noise.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_3year, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc6_3year - mdl53_jc6_3month, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(mdl53_jc6_3year, 21), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_jc6_3year, 126)))'},
    # mdl53_jc6_4year
    # Longer-term default probabilities reflect secular solvency trends that impact long-term equity valuation.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_4year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_4year - mdl53_jc6_6month, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc6_4year, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc6_4year, 252))'},
    # mdl53_jc6_5year
    # The five-year credit horizon aligns with standard CDS maturities, capturing institutional credit pricing shifts.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_5year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc6_5year - mdl53_jc6_3month, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(mdl53_jc6_5year, 21), 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_jc6_5year, 252)))'},
    # mdl53_jc6_6month
    # Six-month credit risk provides a highly sensitive leading indicator of near-term corporate refinancing stress.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_6month, 63))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_jc6_6month - mdl53_jc6_5year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc6_6month, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc6_6month, 21) * rank(ts_delta(close, 5)))'},
    # mdl53_jc6_7year
    # Seven-year default probabilities capture deep structural credit cycle shifts that affect capital-intensive firms.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_7year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_7year - mdl53_jc6_6month, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(mdl53_jc6_7year, 21), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc6_7year, 252))'},
    # mdl53_jm5_10year
    # Ten-year hybrid Jarrow-Merton measures capture long-term solvency trends driven by structural asset-liability mismatches.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_10year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jm5_10year - mdl53_jm5_1year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(mdl53_jm5_10year, 21), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_jm5_10year, 252)))'},
    # mdl53_jm5_1month
    # Ultra-short-term 1-month default risk is highly reactive to immediate liquidity crises and earnings shocks.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_1month, 63))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_jm5_1month - mdl53_jm5_5year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jm5_1month, 10), 10))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jm5_1month, 21) * rank(ts_delta(close, 5)))'},
    # mdl53_jm5_1year
    # One-year hybrid default measures combine equity market volatility and balance sheet metrics to forecast near-term distress.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_1year, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_5year - mdl53_jm5_1year, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jm5_1year, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jm5_1year, 126))'},
    # mdl53_jm5_2year
    # Two-year hybrid credit measures capture the interaction between equity market momentum and structural default barriers.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_2year, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jm5_2year - mdl53_jm5_3month, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(mdl53_jm5_2year, 21), 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_jm5_2year, 126)))'},
    # mdl53_jm5_3month
    # Three-month default probabilities capture short-term stress before it propagates into broader market awareness.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_3month, 63))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_jm5_3month - mdl53_jm5_5year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jm5_3month, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jm5_3month, 63))'},
    # mdl53_jm5_3year
    # Three-year hybrid measures filter out transitory equity noise to isolate persistent changes in credit quality.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_3year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_3year - mdl53_jm5_3month, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(mdl53_jm5_3year, 21), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jm5_3year, 21) * rank(ts_delta(close, 5)))'},
    # mdl53_jm5_4year
    # Four-year default probability trends capture secular shifts in capital structure health and debt sustainability.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_4year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jm5_4year - mdl53_jm5_1year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jm5_4year, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jm5_4year, 252))'},
    # mdl53_jm5_5year
    # The five-year hybrid model provides a robust assessment of structural credit risk, heavily correlated with long-term cost of capital.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_5year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_5year - mdl53_jm5_3month, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(mdl53_jm5_5year, 21), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_jm5_5year, 252)))'},
]

print(f"Total expressions queued: {len(DATA)}")
print("  Batch: llm_model_credit_risk_model53_0528_2331 | 30 fields")
print(f"  Estimated runtime: ~{len(DATA)*1.5:.0f} min")
