# parameters_llm_fundamental_0604_1134.py
# Auto-generated by llm_alpha_generator.py — 20260604_113427
# Model: gemini-3.5-flash | Fields: 20 | Expressions: 150 (incl. auto-TOP200 pairs)
# Run: cp parameters_llm_fundamental_0604_1134.py parameters.py && python3 main.py

from commands import *
BATCH_NAME = 'llm_fundamental_0604_1134'

BASE = {'neutralization': 'SUBINDUSTRY', 'decay': 6, 'truncation': 0.08, 'delay': 1, 'region': 'USA', 'universe': 'TOP3000'}
B500 = {**BASE, 'universe': 'TOP500'}
B200 = {**BASE, 'universe': 'TOP200'}
UNIV = {'TOP3000': BASE, 'TOP500': B500, 'TOP200': B200}

DATA = [
    # accumulated_depreciation_depletion_amortization_ppne
    # A high ratio of accumulated depreciation to market cap indicates older PP&E assets, signaling potential capital expenditure requirements; optimized for TOP200.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(accumulated_depreciation_depletion_amortization_ppne / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(accumulated_depreciation_depletion_amortization_ppne / cap, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(accumulated_depreciation_depletion_amortization_ppne / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(accumulated_depreciation_depletion_amortization_ppne / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(accumulated_depreciation_depletion_amortization_ppne / cap, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(accumulated_depreciation_depletion_amortization_ppne / cap, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(accumulated_depreciation_depletion_amortization_ppne / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(accumulated_depreciation_depletion_amortization_ppne / cap, 252))'},
    # acquisition_total_purchase_price
    # Aggressive spending on acquisitions relative to company size can signal integration risks and potential value destruction.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquisition_total_purchase_price / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquisition_total_purchase_price / cap, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquisition_total_purchase_price / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquisition_total_purchase_price / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquisition_total_purchase_price / cap, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquisition_total_purchase_price / cap, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquisition_total_purchase_price / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquisition_total_purchase_price / cap, 252))'},
    # acquisition_total_purchase_value
    # Large transaction values relative to market cap suggest high capital deployment in M&A, which historically correlates with underperformance; optimized for TOP200.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquisition_total_purchase_value / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquisition_total_purchase_value / cap, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquisition_total_purchase_value / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquisition_total_purchase_value / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquisition_total_purchase_value / cap, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquisition_total_purchase_value / cap, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquisition_total_purchase_value / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquisition_total_purchase_value / cap, 252))'},
    # actual_return_on_pension_plan_assets
    # Strong actual returns on pension assets reduce future corporate funding obligations and improve balance sheet strength.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(actual_return_on_pension_plan_assets / cap, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(actual_return_on_pension_plan_assets / cap, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(actual_return_on_pension_plan_assets / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(actual_return_on_pension_plan_assets / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(actual_return_on_pension_plan_assets / cap, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(actual_return_on_pension_plan_assets / cap, 252)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(actual_return_on_pension_plan_assets / cap, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(actual_return_on_pension_plan_assets / cap, 252))'},
    # afss_accumulated_oci_adjustment_net_tax
    # Positive adjustments to OCI for available-for-sale securities indicate unrealized gains on the investment portfolio, reflecting hidden asset value; optimized for TOP200.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(afss_accumulated_oci_adjustment_net_tax / cap, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(afss_accumulated_oci_adjustment_net_tax / cap, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(afss_accumulated_oci_adjustment_net_tax / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(afss_accumulated_oci_adjustment_net_tax / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(afss_accumulated_oci_adjustment_net_tax / cap, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(afss_accumulated_oci_adjustment_net_tax / cap, 252)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(afss_accumulated_oci_adjustment_net_tax / cap, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(afss_accumulated_oci_adjustment_net_tax / cap, 252))'},
    # allocated_sbp_expense_rsu
    # High stock-based compensation via RSUs dilutes existing shareholders and represents a persistent drag on earnings quality.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(allocated_sbp_expense_rsu / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(allocated_sbp_expense_rsu / cap, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(allocated_sbp_expense_rsu / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(allocated_sbp_expense_rsu / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(allocated_sbp_expense_rsu / cap, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(allocated_sbp_expense_rsu / cap, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(allocated_sbp_expense_rsu / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(allocated_sbp_expense_rsu / cap, 252))'},
    # allocated_sbp_expense_stock_options
    # Elevated stock option expenses represent dilutive compensation models that negatively impact long-term shareholder returns; optimized for TOP200.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(allocated_sbp_expense_stock_options / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(allocated_sbp_expense_stock_options / cap, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(allocated_sbp_expense_stock_options / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(allocated_sbp_expense_stock_options / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(allocated_sbp_expense_stock_options / cap, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(allocated_sbp_expense_stock_options / cap, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(allocated_sbp_expense_stock_options / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(allocated_sbp_expense_stock_options / cap, 252))'},
    # allocated_sbp_expense_total
    # Total share-based compensation expense acts as a significant cash-free expense that dilutes equity value over time.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(allocated_sbp_expense_total / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(allocated_sbp_expense_total / cap, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(allocated_sbp_expense_total / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(allocated_sbp_expense_total / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(allocated_sbp_expense_total / cap, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(allocated_sbp_expense_total / cap, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(allocated_sbp_expense_total / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(allocated_sbp_expense_total / cap, 252))'},
    # allowance_for_doubtful_accounts_2
    # An increasing allowance for doubtful accounts relative to size signals deteriorating customer credit quality and potential future write-downs; optimized for TOP200.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(allowance_for_doubtful_accounts_2 / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(allowance_for_doubtful_accounts_2 / cap, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(allowance_for_doubtful_accounts_2 / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(allowance_for_doubtful_accounts_2 / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(allowance_for_doubtful_accounts_2 / cap, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(allowance_for_doubtful_accounts_2 / cap, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(allowance_for_doubtful_accounts_2 / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(allowance_for_doubtful_accounts_2 / cap, 252))'},
    # amortized_cost_available_securities
    # Higher holdings of available-for-sale securities at amortized cost represent liquid, conservative balance sheet buffers.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(amortized_cost_available_securities / cap, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(amortized_cost_available_securities / cap, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(amortized_cost_available_securities / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(amortized_cost_available_securities / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(amortized_cost_available_securities / cap, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(amortized_cost_available_securities / cap, 252)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(amortized_cost_available_securities / cap, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(amortized_cost_available_securities / cap, 252))'},
    # annual_deferred_income_tax_expense
    # High deferred tax expenses indicate a divergence between book and taxable earnings, signaling lower earnings quality; optimized for TOP200.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(annual_deferred_income_tax_expense / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(annual_deferred_income_tax_expense / cap, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(annual_deferred_income_tax_expense / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(annual_deferred_income_tax_expense / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(annual_deferred_income_tax_expense / cap, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(annual_deferred_income_tax_expense / cap, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(annual_deferred_income_tax_expense / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(annual_deferred_income_tax_expense / cap, 252))'},
    # annual_intangible_amortization_expense_second_year
    # A high level of anticipated intangible amortization in the second year represents a predictable upcoming drag on net profitability.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(annual_intangible_amortization_expense_second_year / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(annual_intangible_amortization_expense_second_year / cap, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(annual_intangible_amortization_expense_second_year / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(annual_intangible_amortization_expense_second_year / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(annual_intangible_amortization_expense_second_year / cap, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(annual_intangible_amortization_expense_second_year / cap, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(annual_intangible_amortization_expense_second_year / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(annual_intangible_amortization_expense_second_year / cap, 252))'},
    # annual_intangible_assets_net_carrying_value
    # High intangible asset carrying values can indicate past overpayment for acquisitions and risk of future write-downs; optimized for TOP200.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(annual_intangible_assets_net_carrying_value / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(annual_intangible_assets_net_carrying_value / cap, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(annual_intangible_assets_net_carrying_value / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(annual_intangible_assets_net_carrying_value / cap, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(annual_intangible_assets_net_carrying_value / cap, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(annual_intangible_assets_net_carrying_value / cap, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(annual_intangible_assets_net_carrying_value / cap, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(annual_intangible_assets_net_carrying_value / cap, 252))'},
    # antidilutive_securities_eps_exclusion_count
    # A high count of excluded antidilutive securities suggests employee stock options are deeply out of the money, reflecting poor historical performance.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(antidilutive_securities_eps_exclusion_count, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(antidilutive_securities_eps_exclusion_count, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(antidilutive_securities_eps_exclusion_count, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(antidilutive_securities_eps_exclusion_count, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(antidilutive_securities_eps_exclusion_count, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(antidilutive_securities_eps_exclusion_count, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(antidilutive_securities_eps_exclusion_count, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(antidilutive_securities_eps_exclusion_count, 252))'},
    # antidilutive_securities_excluded_eps
    # A larger quantity of antidilutive securities excluded from EPS represents a significant potential dilution overhang; optimized for TOP200.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(antidilutive_securities_excluded_eps, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(antidilutive_securities_excluded_eps, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(antidilutive_securities_excluded_eps, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(antidilutive_securities_excluded_eps, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(antidilutive_securities_excluded_eps, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(antidilutive_securities_excluded_eps, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(antidilutive_securities_excluded_eps, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(antidilutive_securities_excluded_eps, 252))'},
    # antidilutive_stock_options_excluded_eps
    # Excluding antidilutive options from EPS reflects conservative accounting and potential overhang, which correlates with long-term performance.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(antidilutive_stock_options_excluded_eps, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(antidilutive_stock_options_excluded_eps, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(antidilutive_stock_options_excluded_eps, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(antidilutive_stock_options_excluded_eps, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(antidilutive_stock_options_excluded_eps, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(antidilutive_stock_options_excluded_eps, 252))'},
    # antidilutive_stock_options_excluded_eps_2
    # A higher count of excluded antidilutive options indicates potential dilution risks and stock-based compensation intensity.
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(antidilutive_stock_options_excluded_eps_2, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(antidilutive_stock_options_excluded_eps_2, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(antidilutive_stock_options_excluded_eps_2, 42) * rank(ts_delta(close, 10)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(antidilutive_stock_options_excluded_eps_2, 42) * rank(ts_delta(close, 10)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(antidilutive_stock_options_excluded_eps_2, 63))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(antidilutive_stock_options_excluded_eps_2, 63))'},
    # assets
    # Total assets represent firm size and asset growth; rapid asset expansion often leads to lower subsequent stock returns due to the asset growth anomaly.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(assets, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(assets, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(assets, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(assets, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(assets, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(assets, 252))'},
    # assets_curr
    # Current assets represent short-term liquidity; changes in current assets can signal working capital efficiency and operational health.
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(assets_curr, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(assets_curr, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(assets_curr, 126))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(assets_curr, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(assets_curr, 63))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(assets_curr, 63))'},
    # assets_fair_value_lvl1
    # Level 1 fair value assets represent highly liquid, market-priced investments, reflecting strong balance sheet quality and lower valuation risk.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(assets_fair_value_lvl1, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(assets_fair_value_lvl1, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(assets_fair_value_lvl1, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(assets_fair_value_lvl1, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(assets_fair_value_lvl1, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(assets_fair_value_lvl1, 252)))'},
]

print(f"Total expressions queued: {len(DATA)}")
print("  Batch: llm_fundamental_0604_1134 | 20 fields")
print(f"  Estimated runtime: ~{len(DATA)*1.5:.0f} min")
