# parameters_llm_model___credit_risk_0528_2328.py
# Auto-generated by llm_alpha_generator.py — 20260528_232805
# Model: gemini-3.5-flash | Fields: 30 | Expressions: 120
# Run: cp parameters_llm_model___credit_risk_0528_2328.py parameters.py && python3 main.py

from commands import *
BATCH_NAME = 'llm_model___credit_risk_0528_2328'

BASE = {'neutralization': 'SUBINDUSTRY', 'decay': 6, 'truncation': 0.08, 'delay': 1, 'region': 'USA', 'universe': 'TOP3000'}
B500 = {**BASE, 'universe': 'TOP500'}
B200 = {**BASE, 'universe': 'TOP200'}
UNIV = {'TOP3000': BASE, 'TOP500': B500, 'TOP200': B200}

DATA = [
    # mdl53_implied_ratings
    # Implied ratings measure credit quality; rating downgrades (increases in numerical risk score) negatively impact equity returns.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_implied_ratings, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_implied_ratings, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_implied_ratings, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_implied_ratings, 126))'},
    # mdl53_implied_spreads
    # Widening implied credit spreads signal escalating default risk, leading to negative momentum in equity prices.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_implied_spreads, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_implied_spreads, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_implied_spreads, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_implied_spreads, 252))'},
    # mdl53_jc5_10year
    # Long-term default probabilities capture secular solvency trends, and steepening of the credit risk curve indicates deteriorating long-term prospects.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_10year - mdl53_jc5_1year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_10year, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_10year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc5_10year, 21), 21))'},
    # mdl53_jc5_1month
    # Very short-term default probability spikes represent acute liquidity squeezes which often mean-revert once resolved.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_jc5_1month - mdl53_jc5_5year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_1month, 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(mdl53_jc5_1month, 10))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc5_1month, 63))'},
    # mdl53_jc5_1year
    # One-year default probability is a highly liquid risk horizon; its acceleration serves as an early warning signal for equity investors.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_1year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_5year - mdl53_jc5_1year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc5_1year, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc5_1year, 252))'},
    # mdl53_jc5_2year
    # The two-year default probability captures medium-term credit cycles, and its spread relative to short-term measures reflects business cycle shifts.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_2year - mdl53_jc5_3month, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_2year, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_2year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc5_2year, 126))'},
    # mdl53_jc5_3month
    # Short-term credit stress captured by the 3-month horizon is highly volatile and mean-reverting when compared to long-term baselines.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_jc5_3month - mdl53_jc5_3year, 42))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_3month, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc5_3month, 10), 10))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc5_3month, 63))'},
    # mdl53_jc5_3year
    # Three-year credit risk measures structural corporate health, with changes in this horizon strongly correlating with long-term equity performance.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_3year - mdl53_jc5_1year, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_3year, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_3year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc5_3year, 126))'},
    # mdl53_jc5_4year
    # The 4-year default probability tracks longer-term credit trends; combining it with price momentum highlights structurally weak firms.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_4year - mdl53_jc5_1year, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_4year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_4year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc5_4year, 252))'},
    # mdl53_jc5_5year
    # The 5-year default probability is the standard benchmark for long-term credit risk, and its spread over the 1-year horizon measures credit curve steepening.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_5year - mdl53_jc5_1year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_5year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_5year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc5_5year, 252))'},
    # mdl53_jc5_6month
    # The 6-month horizon captures near-term liquidity concerns, and its second derivative detects rapid accelerations in credit deterioration.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_6month - mdl53_jc5_5year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_6month, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc5_6month, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc5_6month, 126))'},
    # mdl53_jc5_7year
    # Long-term 7-year default probabilities capture structural solvency shifts that are slow-moving but highly persistent.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_7year - mdl53_jc5_1year, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc5_7year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc5_7year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc5_7year, 252))'},
    # mdl53_jc6_10year
    # The Kamakura Jarrow-Chava v6 model's 10-year horizon provides advanced structural credit risk metrics that help identify long-term equity underperformers.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_10year - mdl53_jc6_1year, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_10year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc6_10year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc6_10year, 252))'},
    # mdl53_jc6_1month
    # Short-term spikes in the Jarrow-Chava v6 1-month model signal temporary credit dislocations that create mean-reversion opportunities.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_jc6_1month - mdl53_jc6_1year, 42))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_1month, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc6_1month, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc6_1month, 63))'},
    # mdl53_jc6_1year
    # The 1-year horizon of the Jarrow-Chava v6 model captures immediate credit risk, where rapid changes strongly dictate equity momentum.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_1year, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc6_1year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc6_1year, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc6_1year, 126))'},
    # mdl53_jc6_2year
    # Medium-term default probability reflects credit risk that interacts with short-term distress and equity momentum.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_2year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc6_2year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc6_2year, 21), 21))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_jc6_3month - mdl53_jc6_2year, 63))'},
    # mdl53_jc6_3month
    # Ultra-short-term default probability captures immediate liquidity distress, which is highly mean-reverting.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_3month, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc6_3month, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(mdl53_jc6_3month, 21), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_jc6_3month, 63)))'},
    # mdl53_jc6_3year
    # The 3-year horizon acts as a transition point between short-term liquidity shocks and structural solvency risk.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_3year, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc6_3year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_3year - mdl53_jc6_3month, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc6_3year, 21), 21))'},
    # mdl53_jc6_4year
    # Longer-term default probabilities are smoothed and represent structural solvency trends when compared to short horizons.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_4year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc6_4year, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_jc6_3month - mdl53_jc6_4year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc6_4year - mdl53_jc6_3month, 21) * rank(ts_delta(close, 5)))'},
    # mdl53_jc6_5year
    # The 5-year default probability is a benchmark structural credit risk metric that captures long-term leverage and business viability.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_5year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_5year - mdl53_jc6_3month, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_jc6_5year, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jc6_5year, 21), 21))'},
    # mdl53_jc6_6month
    # The 6-month horizon captures near-term refinancing risk and working capital constraints.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_6month, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jc6_6month, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(mdl53_jc6_6month, 21), 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jc6_6month, 21) * rank(ts_delta(close, 5)))'},
    # mdl53_jc6_7year
    # Very long-term credit risk models capture secular industry decline and secular macroeconomic shifts.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_7year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jc6_7year - mdl53_jc6_6month, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_jc6_7year, 252)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_jc6_6month - mdl53_jc6_7year, 63))'},
    # mdl53_jm5_10year
    # 10-year structural default probability from hybrid models incorporates equity volatility and long-term debt maturity profiles.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_10year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_10year - mdl53_jm5_1month, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jm5_10year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jm5_10year, 21), 21))'},
    # mdl53_jm5_1month
    # The 1-month horizon is highly sensitive to equity market volatility spikes and sudden liquidity crunches.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_1month, 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(mdl53_jm5_1month, 5), 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jm5_1month, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_jm5_1month, 42)))'},
    # mdl53_jm5_1year
    # One-year default risk represents the standard horizon for commercial credit assessment and near-term solvency.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_1year, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_1year - mdl53_jm5_1month, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jm5_1year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_jm5_1month - mdl53_jm5_1year, 63))'},
    # mdl53_jm5_2year
    # Two-year default probability from the hybrid Jarrow-Merton model captures asset value drift relative to short-term debt.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_2year, 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jm5_2year, 21), 21))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jm5_2year, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_jm5_3month - mdl53_jm5_2year, 63))'},
    # mdl53_jm5_3month
    # Quarterly credit risk measures align with earnings release cycles and capture immediate distress signals.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_3month, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(mdl53_jm5_3month, 21), 126))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jm5_3month, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_jm5_3month, 63)))'},
    # mdl53_jm5_3year
    # Three-year hybrid default metrics reflect structural leverage trends combined with asset volatility dynamics.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_3year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_3year - mdl53_jm5_3month, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jm5_3year - mdl53_jm5_3month, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jm5_3year, 21), 21))'},
    # mdl53_jm5_4year
    # The 4-year credit risk horizon captures business cycle vulnerabilities and longer-term debt rollover risks.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_4year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(mdl53_jm5_4year, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(mdl53_jm5_3month - mdl53_jm5_4year, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(mdl53_jm5_4year, 252)))'},
    # mdl53_jm5_5year
    # Five-year Jarrow-Merton default risk represents a robust structural solvency signal that guides long-term equity performance.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_5year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(mdl53_jm5_5year - mdl53_jm5_1year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(mdl53_jm5_5year, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_delta(ts_delta(mdl53_jm5_5year, 21), 21))'},
]

print(f"Total expressions queued: {len(DATA)}")
print("  Batch: llm_model___credit_risk_0528_2328 | 30 fields")
print(f"  Estimated runtime: ~{len(DATA)*1.5:.0f} min")
