# parameters_llm_analyst_0604_0740.py
# Auto-generated by llm_alpha_generator.py — 20260604_074037
# Model: gemini-3.5-flash | Fields: 20 | Expressions: 150 (incl. auto-TOP200 pairs)
# Run: cp parameters_llm_analyst_0604_0740.py parameters.py && python3 main.py

from commands import *
BATCH_NAME = 'llm_analyst_0604_0740'

BASE = {'neutralization': 'SUBINDUSTRY', 'decay': 6, 'truncation': 0.08, 'delay': 1, 'region': 'USA', 'universe': 'TOP3000'}
B500 = {**BASE, 'universe': 'TOP500'}
B200 = {**BASE, 'universe': 'TOP200'}
UNIV = {'TOP3000': BASE, 'TOP500': B500, 'TOP200': B200}

DATA = [
    # avg_capex_quarterly_estimate
    # Lower capital expenditure estimates often imply higher near-term free cash flow and capital efficiency.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(avg_capex_quarterly_estimate, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(avg_capex_quarterly_estimate, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(avg_capex_quarterly_estimate, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(avg_capex_quarterly_estimate, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(avg_capex_quarterly_estimate, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(avg_capex_quarterly_estimate, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(avg_capex_quarterly_estimate, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(avg_capex_quarterly_estimate, 252))'},
    # avg_ebitda_quarterly_estimate
    # Higher expected EBITDA indicates stronger operating profitability and potential positive earnings momentum.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(avg_ebitda_quarterly_estimate, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(avg_ebitda_quarterly_estimate, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(avg_ebitda_quarterly_estimate, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(avg_ebitda_quarterly_estimate, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(avg_ebitda_quarterly_estimate, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(avg_ebitda_quarterly_estimate, 252)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(avg_ebitda_quarterly_estimate, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(avg_ebitda_quarterly_estimate, 252))'},
    # avg_pretax_profit_quarterly_estimate
    # Increasing pretax profit estimates signal improving corporate margins and operational health.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(avg_pretax_profit_quarterly_estimate, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(avg_pretax_profit_quarterly_estimate, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(avg_pretax_profit_quarterly_estimate, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(avg_pretax_profit_quarterly_estimate, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(avg_pretax_profit_quarterly_estimate, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(avg_pretax_profit_quarterly_estimate, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(avg_pretax_profit_quarterly_estimate, 63))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(avg_pretax_profit_quarterly_estimate, 63))'},
    # avg_total_assets_quarterly_estimate
    # Growth in expected total assets represents expansion of the firm's balance sheet and operational capacity.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(avg_total_assets_quarterly_estimate, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(avg_total_assets_quarterly_estimate, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(avg_total_assets_quarterly_estimate, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(avg_total_assets_quarterly_estimate, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(avg_total_assets_quarterly_estimate, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(avg_total_assets_quarterly_estimate, 252)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(avg_total_assets_quarterly_estimate, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(avg_total_assets_quarterly_estimate, 252))'},
    # basic_shares_max_guidance_qtr
    # Lower share count guidance indicates reduced dilution risk or potential share buybacks.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(basic_shares_max_guidance_qtr, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(basic_shares_max_guidance_qtr, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(basic_shares_max_guidance_qtr, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(basic_shares_max_guidance_qtr, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(basic_shares_max_guidance_qtr, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(basic_shares_max_guidance_qtr, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(basic_shares_max_guidance_qtr, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(basic_shares_max_guidance_qtr, 252))'},
    # book_value_per_share_2
    # High book value per share is a classic value signal representing undervalued equity relative to assets.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(book_value_per_share_2, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(book_value_per_share_2, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(book_value_per_share_2, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(book_value_per_share_2, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(book_value_per_share_2, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(book_value_per_share_2, 252)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(book_value_per_share_2, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(book_value_per_share_2, 252))'},
    # book_value_per_share_avg
    # Average book value estimates smooth out single-broker biases to provide a robust value metric.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(book_value_per_share_avg, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(book_value_per_share_avg, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(book_value_per_share_avg, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(book_value_per_share_avg, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(book_value_per_share_avg, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(book_value_per_share_avg, 252)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(book_value_per_share_avg, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(book_value_per_share_avg, 252))'},
    # book_value_per_share_max
    # Optimistic book value estimates reflect potential hidden asset value recognized by leading analysts.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(book_value_per_share_max, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(book_value_per_share_max, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(book_value_per_share_max, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(book_value_per_share_max, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(book_value_per_share_max, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(book_value_per_share_max, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(book_value_per_share_max, 63))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(book_value_per_share_max, 63))'},
    # book_value_per_share_median
    # Median analyst estimates of book value filter out extreme outliers for a more reliable consensus signal.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(book_value_per_share_median, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(book_value_per_share_median, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(book_value_per_share_median, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(book_value_per_share_median, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(book_value_per_share_median, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(book_value_per_share_median, 252)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(book_value_per_share_median, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(book_value_per_share_median, 252))'},
    # book_value_per_share_min
    # The most conservative estimate of book value per share provides a highly robust margin-of-safety value signal.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(book_value_per_share_min, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(book_value_per_share_min, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(book_value_per_share_min, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(book_value_per_share_min, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(book_value_per_share_min, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(book_value_per_share_min, 252)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(book_value_per_share_min, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(book_value_per_share_min, 252))'},
    # book_value_per_share_min_guidance_qtr
    # Minimum guidance values for book value represent a reliable floor for asset-based valuation models.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(book_value_per_share_min_guidance_qtr, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(book_value_per_share_min_guidance_qtr, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(book_value_per_share_min_guidance_qtr, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(book_value_per_share_min_guidance_qtr, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(hump(ts_rank(book_value_per_share_min_guidance_qtr, 252)))'},
    {**UNIV['TOP200'], 'code': 'rank(hump(ts_rank(book_value_per_share_min_guidance_qtr, 252)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(book_value_per_share_min_guidance_qtr, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(book_value_per_share_min_guidance_qtr, 252))'},
    # book_value_per_share_reported_value
    # Actual reported book value per share provides a concrete fundamental anchor for cross-sectional value strategies.
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(book_value_per_share_reported_value, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(book_value_per_share_reported_value, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(book_value_per_share_reported_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(book_value_per_share_reported_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(book_value_per_share_reported_value, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(book_value_per_share_reported_value, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(book_value_per_share_reported_value, 63))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(book_value_per_share_reported_value, 63))'},
    # capital_expenditure_amount
    # Firms with lower trailing capital expenditures often demonstrate higher free cash flow conversion rates.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(capital_expenditure_amount, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(capital_expenditure_amount, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(capital_expenditure_amount, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(capital_expenditure_amount, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(capital_expenditure_amount, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(capital_expenditure_amount, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(capital_expenditure_amount, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(capital_expenditure_amount, 252))'},
    # capital_expenditure_guidance_value
    # Conservative capital expenditure guidance signals management focus on profitability over aggressive asset expansion.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(capital_expenditure_guidance_value, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(capital_expenditure_guidance_value, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(capital_expenditure_guidance_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(capital_expenditure_guidance_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(capital_expenditure_guidance_value, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(capital_expenditure_guidance_value, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(capital_expenditure_guidance_value, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(capital_expenditure_guidance_value, 252))'},
    # capital_expenditure_max
    # Avoiding firms with extremely high maximum capex estimates protects against capital-intensive, low-margin business models.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(capital_expenditure_max, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(capital_expenditure_max, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(capital_expenditure_max, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(capital_expenditure_max, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(capital_expenditure_max, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(capital_expenditure_max, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(capital_expenditure_max, 63))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(capital_expenditure_max, 63))'},
    # capital_expenditure_max_guidance_qtr
    # Tracking changes in the ceiling of management's CapEx guidance captures aggressive growth expectations and investment cycles.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(capital_expenditure_max_guidance_qtr, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(capital_expenditure_max_guidance_qtr, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(capital_expenditure_max_guidance_qtr, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(capital_expenditure_max_guidance_qtr, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(capital_expenditure_max_guidance_qtr, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(capital_expenditure_max_guidance_qtr, 252))'},
    # capital_expenditure_median
    # Median CapEx estimates represent the consensus expectation of investment, which when paired with price momentum identifies value-creating expanders.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(capital_expenditure_median, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(capital_expenditure_median, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(capital_expenditure_median, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(capital_expenditure_median, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(capital_expenditure_median, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(capital_expenditure_median, 252)))'},
    # capital_expenditure_min
    # The floor of projected capital expenditures indicates the minimum commitment to long-term assets, showing baseline business stability.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(capital_expenditure_min, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(capital_expenditure_min, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(capital_expenditure_min, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(capital_expenditure_min, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(capital_expenditure_min, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(capital_expenditure_min, 252))'},
    # capital_expenditure_reported_value
    # Actual historical cash outflows for CapEx scaled over time reveal the realized investment intensity of the firm.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(capital_expenditure_reported_value, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(capital_expenditure_reported_value, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(capital_expenditure_reported_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(capital_expenditure_reported_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(capital_expenditure_reported_value, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(capital_expenditure_reported_value, 252)))'},
    # capital_expenditure_stddev
    # High dispersion in CapEx estimates signals analyst uncertainty regarding the firm's future projects and capital allocation efficiency.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(capital_expenditure_stddev, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(capital_expenditure_stddev, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(capital_expenditure_stddev, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(capital_expenditure_stddev, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(capital_expenditure_stddev, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(capital_expenditure_stddev, 252))'},
]

print(f"Total expressions queued: {len(DATA)}")
print("  Batch: llm_analyst_0604_0740 | 20 fields")
print(f"  Estimated runtime: ~{len(DATA)*1.5:.0f} min")
