# parameters_llm_fundamental_0602_2105.py
# Auto-generated by llm_alpha_generator.py — 20260602_210511
# Model: gemini-3.5-flash | Fields: 20 | Expressions: 160 (incl. auto-TOP200 pairs)
# Run: cp parameters_llm_fundamental_0602_2105.py parameters.py && python3 main.py

from commands import *
BATCH_NAME = 'llm_fundamental_0602_2105'

BASE = {'neutralization': 'SUBINDUSTRY', 'decay': 6, 'truncation': 0.08, 'delay': 1, 'region': 'USA', 'universe': 'TOP3000'}
B500 = {**BASE, 'universe': 'TOP500'}
B200 = {**BASE, 'universe': 'TOP200'}
UNIV = {'TOP3000': BASE, 'TOP500': B500, 'TOP200': B200}

DATA = [
    # accrued_liabilities_total
    # High accrued liabilities indicate unpaid obligations which can signal cash flow pressure or aggressive expense management.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(accrued_liabilities_total, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(accrued_liabilities_total, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(accrued_liabilities_total, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(accrued_liabilities_total, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(accrued_liabilities_total, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(accrued_liabilities_total, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(accrued_liabilities_total, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(accrued_liabilities_total, 252))'},
    # accrued_liabilities_total_2
    # Tracking changes in unpaid incurred liabilities reveals working capital efficiency and potential liquidity constraints.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(accrued_liabilities_total_2, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(accrued_liabilities_total_2, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(accrued_liabilities_total_2, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(accrued_liabilities_total_2, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(accrued_liabilities_total_2, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(accrued_liabilities_total_2, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(accrued_liabilities_total_2, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(accrued_liabilities_total_2, 252))'},
    # accumulated_amortization_customer_intangibles
    # Accumulated amortization of customer intangibles reflects the historical decay of acquired customer relationship values.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(accumulated_amortization_customer_intangibles, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(accumulated_amortization_customer_intangibles, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(accumulated_amortization_customer_intangibles, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(accumulated_amortization_customer_intangibles, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(accumulated_amortization_customer_intangibles, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(accumulated_amortization_customer_intangibles, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(accumulated_amortization_customer_intangibles, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(accumulated_amortization_customer_intangibles, 252))'},
    # accumulated_amortization_customer_intangibles_2
    # Amortization of customer-related intangibles indicates the rate at which acquired customer asset values are being written down.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(accumulated_amortization_customer_intangibles_2, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(accumulated_amortization_customer_intangibles_2, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(accumulated_amortization_customer_intangibles_2, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(accumulated_amortization_customer_intangibles_2, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(accumulated_amortization_customer_intangibles_2, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(accumulated_amortization_customer_intangibles_2, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(accumulated_amortization_customer_intangibles_2, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(accumulated_amortization_customer_intangibles_2, 252))'},
    # accumulated_amortization_finite_intangibles
    # Accumulated amortization of finite-lived intangibles measures the depletion of acquired non-physical assets over time.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(accumulated_amortization_finite_intangibles, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(accumulated_amortization_finite_intangibles, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(accumulated_amortization_finite_intangibles, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(accumulated_amortization_finite_intangibles, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(accumulated_amortization_finite_intangibles, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(accumulated_amortization_finite_intangibles, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(accumulated_amortization_finite_intangibles, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(accumulated_amortization_finite_intangibles, 252))'},
    # accumulated_depreciation_depletion_amortization_ppne
    # High accumulated PP&E depreciation and depletion can signal aging physical infrastructure requiring imminent capital expenditure.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(accumulated_depreciation_depletion_amortization_ppne, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(accumulated_depreciation_depletion_amortization_ppne, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(accumulated_depreciation_depletion_amortization_ppne, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(accumulated_depreciation_depletion_amortization_ppne, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(accumulated_depreciation_depletion_amortization_ppne, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(accumulated_depreciation_depletion_amortization_ppne, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(accumulated_depreciation_depletion_amortization_ppne, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(accumulated_depreciation_depletion_amortization_ppne, 252))'},
    # accumulated_oci_net_of_tax_value
    # Accumulated other comprehensive income captures unrealized gains or losses, reflecting hidden balance sheet strength or vulnerability.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(accumulated_oci_net_of_tax_value, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(accumulated_oci_net_of_tax_value, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(accumulated_oci_net_of_tax_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(accumulated_oci_net_of_tax_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(accumulated_oci_net_of_tax_value, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(accumulated_oci_net_of_tax_value, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(accumulated_oci_net_of_tax_value, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(accumulated_oci_net_of_tax_value, 252))'},
    # acquired_cash_equivalents_business_combination
    # Cash acquired through business combinations provides immediate liquidity post-transaction, impacting near-term valuation.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquired_cash_equivalents_business_combination, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquired_cash_equivalents_business_combination, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquired_cash_equivalents_business_combination, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquired_cash_equivalents_business_combination, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquired_cash_equivalents_business_combination, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquired_cash_equivalents_business_combination, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquired_cash_equivalents_business_combination, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquired_cash_equivalents_business_combination, 252))'},
    # acquired_finite_intangible_assets
    # The acquisition of finite-lived intangible assets reflects strategic investments in proprietary technology, patents, or brands.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquired_finite_intangible_assets, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquired_finite_intangible_assets, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquired_finite_intangible_assets, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquired_finite_intangible_assets, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquired_finite_intangible_assets, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquired_finite_intangible_assets, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquired_finite_intangible_assets, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquired_finite_intangible_assets, 252))'},
    # acquired_finite_intangible_assets_total
    # Total acquired finite-lived intangibles represent the scale of non-physical strategic assets added via M&A.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquired_finite_intangible_assets_total, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquired_finite_intangible_assets_total, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquired_finite_intangible_assets_total, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquired_finite_intangible_assets_total, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquired_finite_intangible_assets_total, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquired_finite_intangible_assets_total, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquired_finite_intangible_assets_total, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquired_finite_intangible_assets_total, 252))'},
    # acquired_goodwill_value
    # Acquired goodwill measures the premium paid over book value in acquisitions, which can lead to future impairment risks if overvalued.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquired_goodwill_value, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquired_goodwill_value, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquired_goodwill_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquired_goodwill_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquired_goodwill_value, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquired_goodwill_value, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquired_goodwill_value, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquired_goodwill_value, 252))'},
    # acquired_intangible_avg_useful_life
    # The average useful life of acquired intangibles determines the long-term amortization drag on future earnings.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquired_intangible_avg_useful_life, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquired_intangible_avg_useful_life, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquired_intangible_avg_useful_life, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquired_intangible_avg_useful_life, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquired_intangible_avg_useful_life, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquired_intangible_avg_useful_life, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquired_intangible_avg_useful_life, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquired_intangible_avg_useful_life, 252))'},
    # acquired_property_equipment_value
    # The value of acquired PP&E indicates the physical asset expansion achieved through corporate acquisitions.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquired_property_equipment_value, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquired_property_equipment_value, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquired_property_equipment_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquired_property_equipment_value, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquired_property_equipment_value, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquired_property_equipment_value, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquired_property_equipment_value, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquired_property_equipment_value, 252))'},
    # acquisition_assets_property_plant_equipment
    # Acquisition of physical plant and equipment assets represents tangible capacity expansion via M&A activity.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquisition_assets_property_plant_equipment, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquisition_assets_property_plant_equipment, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquisition_assets_property_plant_equipment, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquisition_assets_property_plant_equipment, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquisition_assets_property_plant_equipment, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquisition_assets_property_plant_equipment, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquisition_assets_property_plant_equipment, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquisition_assets_property_plant_equipment, 252))'},
    # acquisition_goodwill_amount
    # The volume of goodwill generated in acquisitions reflects management's premium spending on strategic M&A.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquisition_goodwill_amount, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquisition_goodwill_amount, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquisition_goodwill_amount, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquisition_goodwill_amount, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquisition_goodwill_amount, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquisition_goodwill_amount, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquisition_goodwill_amount, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquisition_goodwill_amount, 252))'},
    # acquisition_identifiable_assets_recognized
    # Large acquired assets can indicate aggressive over-expansion; neutralizing this with price momentum or z-scores helps capture post-acquisition digestion phases.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquisition_identifiable_assets_recognized, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquisition_identifiable_assets_recognized, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquisition_identifiable_assets_recognized, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquisition_identifiable_assets_recognized, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquisition_identifiable_assets_recognized, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquisition_identifiable_assets_recognized, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquisition_identifiable_assets_recognized, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquisition_identifiable_assets_recognized, 252))'},
    # acquisition_liabilities_assumed
    # Assuming heavy liabilities during acquisitions increases structural risk, which typically correlates with long-term underperformance.
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquisition_liabilities_assumed, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquisition_liabilities_assumed, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquisition_liabilities_assumed, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquisition_liabilities_assumed, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquisition_liabilities_assumed, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquisition_liabilities_assumed, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquisition_liabilities_assumed, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquisition_liabilities_assumed, 252))'},
    # acquisition_proforma_revenue
    # Pro forma revenue adjustments reflect theoretical growth, where deviations from actual trend lines generate significant pricing anomalies.
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquisition_proforma_revenue, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquisition_proforma_revenue, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquisition_proforma_revenue, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquisition_proforma_revenue, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquisition_proforma_revenue, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquisition_proforma_revenue, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquisition_proforma_revenue, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquisition_proforma_revenue, 252))'},
    # acquisition_related_costs_expense
    # Spikes in transaction-related costs act as an immediate drag on operating margins, creating short-term mean-reversion opportunities.
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquisition_related_costs_expense, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquisition_related_costs_expense, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquisition_related_costs_expense, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquisition_related_costs_expense, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquisition_related_costs_expense, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquisition_related_costs_expense, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquisition_related_costs_expense, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquisition_related_costs_expense, 252)))'},
    # acquisition_related_expenses
    # Acquisition expenses compress near-term profitability; tracking this via short-lookback and z-score templates helps isolate temporary earnings shocks.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(acquisition_related_expenses, 63))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(acquisition_related_expenses, 63))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(acquisition_related_expenses, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(acquisition_related_expenses, 21) * rank(ts_delta(close, 5)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(acquisition_related_expenses, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(acquisition_related_expenses, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(acquisition_related_expenses, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(acquisition_related_expenses, 252)))'},
]

print(f"Total expressions queued: {len(DATA)}")
print("  Batch: llm_fundamental_0602_2105 | 20 fields")
print(f"  Estimated runtime: ~{len(DATA)*1.5:.0f} min")
