# parameters_llm_fundamental_0605_2331.py
# Auto-generated by llm_alpha_generator.py — 20260605_233152
# Model: gemini-3.5-flash | Fields: 20 | Expressions: 200 (incl. auto-TOP200 pairs)
# Run: cp parameters_llm_fundamental_0605_2331.py parameters.py && python3 main.py

from commands import *
BATCH_NAME = 'llm_fundamental_0605_2331'

BASE = {'neutralization': 'SUBINDUSTRY', 'decay': 6, 'truncation': 0.08, 'delay': 1, 'region': 'USA', 'universe': 'TOP3000'}
B500 = {**BASE, 'universe': 'TOP500'}
B200 = {**BASE, 'universe': 'TOP200'}
UNIV = {'TOP3000': BASE, 'TOP500': B500, 'TOP200': B200}

DATA = [
    # accumulated_depreciation_depletion_amortization_ppne
    # Measures the trend slope and peer-relative level of accumulated depreciation, reflecting asset aging and capital reinvestment cycles.
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(accumulated_depreciation_depletion_amortization_ppne, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(accumulated_depreciation_depletion_amortization_ppne, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_regression(accumulated_depreciation_depletion_amortization_ppne, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_regression(accumulated_depreciation_depletion_amortization_ppne, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_rank(accumulated_depreciation_depletion_amortization_ppne, 252), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_rank(accumulated_depreciation_depletion_amortization_ppne, 252), industry))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(ts_zscore(accumulated_depreciation_depletion_amortization_ppne, 252), 22))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(ts_zscore(accumulated_depreciation_depletion_amortization_ppne, 252), 22))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(accumulated_depreciation_depletion_amortization_ppne, 120), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(accumulated_depreciation_depletion_amortization_ppne, 120), 252))'},
    # acquisition_total_purchase_price
    # Uses backfilled acquisition purchase price to capture strategic corporate expansion and investment intensity relative to peers.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(acquisition_total_purchase_price, 120), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(acquisition_total_purchase_price, 120), 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(ts_backfill(acquisition_total_purchase_price, 120), 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(ts_backfill(acquisition_total_purchase_price, 120), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_zscore(ts_backfill(acquisition_total_purchase_price, 120), 252), subindustry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_zscore(ts_backfill(acquisition_total_purchase_price, 120), 252), subindustry))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_decay_linear(ts_zscore(ts_backfill(acquisition_total_purchase_price, 120), 126), 22))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_decay_linear(ts_zscore(ts_backfill(acquisition_total_purchase_price, 120), 126), 22))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(ts_backfill(acquisition_total_purchase_price, 120), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(ts_backfill(acquisition_total_purchase_price, 120), ts_step(1), 252, rettype=2))'},
    # acquisition_total_purchase_value
    # Tracks the correlation and volatility of total acquisition purchase values to identify aggressive consolidators and their market-price linkage.
    {**UNIV['TOP3000'], 'code': '-rank(ts_corr(ts_backfill(acquisition_total_purchase_value, 120), close, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_corr(ts_backfill(acquisition_total_purchase_value, 120), close, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_corr(ts_backfill(acquisition_total_purchase_value, 120), close, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_corr(ts_backfill(acquisition_total_purchase_value, 120), close, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_backfill(acquisition_total_purchase_value, 120), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_backfill(acquisition_total_purchase_value, 120), industry))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_std_dev(ts_backfill(acquisition_total_purchase_value, 120), 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_std_dev(ts_backfill(acquisition_total_purchase_value, 120), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(acquisition_total_purchase_value, 120), 252) * rank(ts_delta(close, 22)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(acquisition_total_purchase_value, 120), 252) * rank(ts_delta(close, 22)))'},
    # actual_return_on_pension_plan_assets
    # Captures the efficiency and growth of pension plan asset returns, which can impact future corporate earnings through reduced funding liabilities.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(actual_return_on_pension_plan_assets, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(actual_return_on_pension_plan_assets, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(actual_return_on_pension_plan_assets, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(actual_return_on_pension_plan_assets, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_zscore(actual_return_on_pension_plan_assets, 252), sector))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_zscore(actual_return_on_pension_plan_assets, 252), sector))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_regression(actual_return_on_pension_plan_assets, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_regression(actual_return_on_pension_plan_assets, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_zscore(actual_return_on_pension_plan_assets, 126), 22) * rank(ts_delta(close, 22)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_zscore(actual_return_on_pension_plan_assets, 126), 22) * rank(ts_delta(close, 22)))'},
    # afss_accumulated_oci_adjustment_net_tax
    # Measures changes in available-for-sale securities value via OCI adjustments, indicating non-operating balance sheet strength or hidden risks.
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(afss_accumulated_oci_adjustment_net_tax, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(afss_accumulated_oci_adjustment_net_tax, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(afss_accumulated_oci_adjustment_net_tax, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(afss_accumulated_oci_adjustment_net_tax, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_rank(afss_accumulated_oci_adjustment_net_tax, 252), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_rank(afss_accumulated_oci_adjustment_net_tax, 252), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_std_dev(afss_accumulated_oci_adjustment_net_tax, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_std_dev(afss_accumulated_oci_adjustment_net_tax, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_regression(afss_accumulated_oci_adjustment_net_tax, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_regression(afss_accumulated_oci_adjustment_net_tax, ts_step(1), 252, rettype=2))'},
    # allocated_sbp_expense_rsu
    # Evaluates stock-based compensation trends through RSUs, signaling talent retention strategies and potential future equity dilution.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(allocated_sbp_expense_rsu, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(allocated_sbp_expense_rsu, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(allocated_sbp_expense_rsu, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(allocated_sbp_expense_rsu, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_zscore(allocated_sbp_expense_rsu, 252), subindustry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_zscore(allocated_sbp_expense_rsu, 252), subindustry))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_regression(allocated_sbp_expense_rsu, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_regression(allocated_sbp_expense_rsu, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(allocated_sbp_expense_rsu, 63))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(allocated_sbp_expense_rsu, 63))'},
    # allocated_sbp_expense_stock_options
    # Monitors stock option compensation volatility and industry-relative levels to assess management alignment and dilution dynamics.
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(allocated_sbp_expense_stock_options, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(allocated_sbp_expense_stock_options, 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_zscore(allocated_sbp_expense_stock_options, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_zscore(allocated_sbp_expense_stock_options, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_rank(allocated_sbp_expense_stock_options, 126), sector))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_rank(allocated_sbp_expense_stock_options, 126), sector))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_std_dev(allocated_sbp_expense_stock_options, 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_std_dev(allocated_sbp_expense_stock_options, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_corr(allocated_sbp_expense_stock_options, close, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_corr(allocated_sbp_expense_stock_options, close, 252))'},
    # allocated_sbp_expense_total
    # Examines total stock-based compensation trends to distinguish high-growth talent-heavy firms from those with excessive dilutive practices.
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(allocated_sbp_expense_total, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(allocated_sbp_expense_total, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_regression(allocated_sbp_expense_total, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_regression(allocated_sbp_expense_total, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_rank(allocated_sbp_expense_total, 252), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_rank(allocated_sbp_expense_total, 252), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_zscore(allocated_sbp_expense_total, 252), 44) * rank(ts_delta(close, 22)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_zscore(allocated_sbp_expense_total, 252), 44) * rank(ts_delta(close, 22)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(ts_backfill(allocated_sbp_expense_total, 120), 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(ts_backfill(allocated_sbp_expense_total, 120), 252))'},
    # allowance_for_doubtful_accounts_2
    # An increasing trend in the allowance for doubtful accounts signals deteriorating customer credit quality and potential future revenue write-offs.
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(ts_backfill(allowance_for_doubtful_accounts_2, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(ts_backfill(allowance_for_doubtful_accounts_2, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_regression(ts_backfill(allowance_for_doubtful_accounts_2, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_regression(ts_backfill(allowance_for_doubtful_accounts_2, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_zscore(ts_backfill(allowance_for_doubtful_accounts_2, 252), 252), subindustry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_zscore(ts_backfill(allowance_for_doubtful_accounts_2, 252), 252), subindustry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(allowance_for_doubtful_accounts_2, 252), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(allowance_for_doubtful_accounts_2, 252), 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(ts_backfill(allowance_for_doubtful_accounts_2, 252), 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(ts_backfill(allowance_for_doubtful_accounts_2, 252), 252))'},
    # amortized_cost_available_securities
    # The trend and volatility of amortized cost of available-for-sale securities reflect the firm's conservative capital allocation and exposure to interest rate risks.
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_rank(amortized_cost_available_securities, 252), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_rank(amortized_cost_available_securities, 252), industry))'},
    {**UNIV['TOP3000'], 'code': 'rank(group_rank(ts_rank(amortized_cost_available_securities, 252), industry))'},
    {**UNIV['TOP200'], 'code': 'rank(group_rank(ts_rank(amortized_cost_available_securities, 252), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_std_dev(ts_backfill(amortized_cost_available_securities, 252), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_std_dev(ts_backfill(amortized_cost_available_securities, 252), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_corr(amortized_cost_available_securities, close, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_corr(amortized_cost_available_securities, close, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(amortized_cost_available_securities, 126), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_delta(amortized_cost_available_securities, 126), 252))'},
    # annual_deferred_income_tax_expense
    # Deferred tax expense changes reveal differences between book and tax accounting, highlighting potential earnings management or future cash outflows.
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(ts_backfill(annual_deferred_income_tax_expense, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(ts_backfill(annual_deferred_income_tax_expense, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_regression(ts_backfill(annual_deferred_income_tax_expense, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_regression(ts_backfill(annual_deferred_income_tax_expense, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_zscore(annual_deferred_income_tax_expense, 252), sector))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_zscore(annual_deferred_income_tax_expense, 252), sector))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(annual_deferred_income_tax_expense, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(annual_deferred_income_tax_expense, 252)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(annual_deferred_income_tax_expense, 63) * rank(ts_delta(close, 22)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(annual_deferred_income_tax_expense, 63) * rank(ts_delta(close, 22)))'},
    # annual_intangible_amortization_expense_second_year
    # Second-year forward amortization of intangible assets measures the expected decay of acquired assets, impacting future net income projections.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(annual_intangible_amortization_expense_second_year, 504), 504))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(annual_intangible_amortization_expense_second_year, 504), 504))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(ts_backfill(annual_intangible_amortization_expense_second_year, 504), 504))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(ts_backfill(annual_intangible_amortization_expense_second_year, 504), 504))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_zscore(annual_intangible_amortization_expense_second_year, 252), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_zscore(annual_intangible_amortization_expense_second_year, 252), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_std_dev(annual_intangible_amortization_expense_second_year, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_std_dev(annual_intangible_amortization_expense_second_year, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_corr(annual_intangible_amortization_expense_second_year, returns, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_corr(annual_intangible_amortization_expense_second_year, returns, 252))'},
    # annual_intangible_assets_net_carrying_value
    # The trend in the net carrying value of intangible assets identifies companies actively investing in or writing down their intellectual property.
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(ts_backfill(annual_intangible_assets_net_carrying_value, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(ts_backfill(annual_intangible_assets_net_carrying_value, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_regression(ts_backfill(annual_intangible_assets_net_carrying_value, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_regression(ts_backfill(annual_intangible_assets_net_carrying_value, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_rank(annual_intangible_assets_net_carrying_value, 252), subindustry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_rank(annual_intangible_assets_net_carrying_value, 252), subindustry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(annual_intangible_assets_net_carrying_value, 126), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_delta(annual_intangible_assets_net_carrying_value, 126), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(annual_intangible_assets_net_carrying_value, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(annual_intangible_assets_net_carrying_value, 252))'},
    # antidilutive_securities_eps_exclusion_count
    # An increasing count of excluded antidilutive securities suggests that outstanding options or convertible debt are out-of-the-money, signaling weak stock performance.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_backfill(antidilutive_securities_eps_exclusion_count, 252), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_backfill(antidilutive_securities_eps_exclusion_count, 252), 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(ts_backfill(antidilutive_securities_eps_exclusion_count, 252), 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(ts_backfill(antidilutive_securities_eps_exclusion_count, 252), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_rank(antidilutive_securities_eps_exclusion_count, 252), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_rank(antidilutive_securities_eps_exclusion_count, 252), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(antidilutive_securities_eps_exclusion_count, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(antidilutive_securities_eps_exclusion_count, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(hump(ts_rank(antidilutive_securities_eps_exclusion_count, 252)))'},
    {**UNIV['TOP200'], 'code': '-rank(hump(ts_rank(antidilutive_securities_eps_exclusion_count, 252)))'},
    # antidilutive_securities_excluded_eps
    # Changes in the volume of antidilutive securities excluded from EPS reveal shifts in the company's capital structure and option moneyness relative to peer groups.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(antidilutive_securities_excluded_eps, 126), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_delta(antidilutive_securities_excluded_eps, 126), 252))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(ts_delta(antidilutive_securities_excluded_eps, 126), 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(ts_delta(antidilutive_securities_excluded_eps, 126), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_zscore(antidilutive_securities_excluded_eps, 252), sector))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_zscore(antidilutive_securities_excluded_eps, 252), sector))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_std_dev(antidilutive_securities_excluded_eps, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_std_dev(antidilutive_securities_excluded_eps, 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_corr(antidilutive_securities_excluded_eps, close, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_corr(antidilutive_securities_excluded_eps, close, 252))'},
    # antidilutive_stock_options_excluded_eps
    # The trend of excluded antidilutive stock options serves as a proxy for employee compensation structure and option overhang relative to industry peers.
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(ts_backfill(antidilutive_stock_options_excluded_eps, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(ts_backfill(antidilutive_stock_options_excluded_eps, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_regression(ts_backfill(antidilutive_stock_options_excluded_eps, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_regression(ts_backfill(antidilutive_stock_options_excluded_eps, 252), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_rank(antidilutive_stock_options_excluded_eps, 252), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_rank(antidilutive_stock_options_excluded_eps, 252), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(antidilutive_stock_options_excluded_eps, 63) * rank(ts_delta(close, 22)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(antidilutive_stock_options_excluded_eps, 63) * rank(ts_delta(close, 22)))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_zscore(antidilutive_stock_options_excluded_eps, 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_zscore(antidilutive_stock_options_excluded_eps, 252))'},
    # antidilutive_stock_options_excluded_eps_2
    # The trend and volatility of excluded antidilutive options signal changes in management's equity compensation expectations and underlying equity valuation.
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(antidilutive_stock_options_excluded_eps_2, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(antidilutive_stock_options_excluded_eps_2, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_regression(antidilutive_stock_options_excluded_eps_2, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_regression(antidilutive_stock_options_excluded_eps_2, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_rank(ts_backfill(antidilutive_stock_options_excluded_eps_2, 126), 252), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_rank(ts_backfill(antidilutive_stock_options_excluded_eps_2, 126), 252), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_zscore(antidilutive_stock_options_excluded_eps_2, 252), 22) * rank(ts_delta(close, 22)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_zscore(antidilutive_stock_options_excluded_eps_2, 252), 22) * rank(ts_delta(close, 22)))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_std_dev(ts_backfill(antidilutive_stock_options_excluded_eps_2, 126), 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_std_dev(ts_backfill(antidilutive_stock_options_excluded_eps_2, 126), 252))'},
    # assets
    # Asset growth rate of change and trend slope capture corporate expansion efficiency relative to industry peers.
    {**UNIV['TOP3000'], 'code': '-rank(ts_rank(ts_delta(assets, 252), 504))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_rank(ts_delta(assets, 252), 504))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(ts_delta(assets, 252), 504))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(ts_delta(assets, 252), 504))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_regression(assets, ts_step(1), 504, rettype=2), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_regression(assets, ts_step(1), 504, rettype=2), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_zscore(assets, 252), 22) * rank(ts_delta(close, 22)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_zscore(assets, 252), 22) * rank(ts_delta(close, 22)))'},
    {**UNIV['TOP3000'], 'code': 'rank(group_zscore(ts_rank(assets, 252), sector))'},
    {**UNIV['TOP200'], 'code': 'rank(group_zscore(ts_rank(assets, 252), sector))'},
    # assets_curr
    # The trend and volatility of highly liquid current assets reflect short-term operational safety and capital allocation efficiency.
    {**UNIV['TOP3000'], 'code': '-rank(ts_regression(assets_curr, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_regression(assets_curr, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_regression(assets_curr, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_regression(assets_curr, ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_zscore(ts_rank(assets_curr, 252), subindustry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_zscore(ts_rank(assets_curr, 252), subindustry))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_rank(ts_corr(assets_curr, returns, 126), 252))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_rank(ts_corr(assets_curr, returns, 126), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_zscore(assets_curr, 126), 22) * rank(ts_delta(close, 22)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_zscore(assets_curr, 126), 22) * rank(ts_delta(close, 22)))'},
    # assets_fair_value_lvl1
    # The growth and stability of transparent, market-quoted Level 1 assets indicate lower valuation risk and robust balance sheet liquidity.
    {**UNIV['TOP3000'], 'code': 'rank(group_rank(ts_zscore(ts_backfill(assets_fair_value_lvl1, 126), 252), industry))'},
    {**UNIV['TOP200'], 'code': 'rank(group_rank(ts_zscore(ts_backfill(assets_fair_value_lvl1, 126), 252), industry))'},
    {**UNIV['TOP3000'], 'code': '-rank(group_rank(ts_zscore(ts_backfill(assets_fair_value_lvl1, 126), 252), industry))'},
    {**UNIV['TOP200'], 'code': '-rank(group_rank(ts_zscore(ts_backfill(assets_fair_value_lvl1, 126), 252), industry))'},
    {**UNIV['TOP3000'], 'code': 'rank(ts_regression(ts_backfill(assets_fair_value_lvl1, 126), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP200'], 'code': 'rank(ts_regression(ts_backfill(assets_fair_value_lvl1, 126), ts_step(1), 252, rettype=2))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_std_dev(ts_backfill(assets_fair_value_lvl1, 126), 252))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_std_dev(ts_backfill(assets_fair_value_lvl1, 126), 252))'},
    {**UNIV['TOP3000'], 'code': '-rank(ts_decay_linear(ts_zscore(ts_backfill(assets_fair_value_lvl1, 126), 252), 22) * rank(ts_delta(close, 22)))'},
    {**UNIV['TOP200'], 'code': '-rank(ts_decay_linear(ts_zscore(ts_backfill(assets_fair_value_lvl1, 126), 252), 22) * rank(ts_delta(close, 22)))'},
]

print(f"Total expressions queued: {len(DATA)}")
print("  Batch: llm_fundamental_0605_2331 | 20 fields")
print(f"  Estimated runtime: ~{len(DATA)*1.5:.0f} min")
